// Registry view types (BUILD-GUIDE 6.6): the generated client's types for the /v1/models routes
// (services/platform/nf_platform/api/registry_routes.py), regenerated by scripts/gen-api.mjs.
export type {
  ContextIn,
  DeploymentIn,
  DeploymentOut,
  FlagOut,
  ManifestSummary,
  Measurement,
  ModelCard,
  ModelDetailOut,
  ModelOut,
  VersionOut,
  VersionSummary,
  VocabularyOut,
} from '../api/generated';
