// GENERATED by apps/console/scripts/gen-api.mjs from the platform FastAPI app. Do not edit.
// Regenerate: node apps/console/scripts/gen-api.mjs (a test fails on drift).
/* eslint-disable */

export const API_TITLE = 'Platform API';
export const API_VERSION = '1.0.0';

export type AcceptedOut = {
  status?: 'pending-confirmation';
};

export type ApiKeyIn = {
  /** 1..365, default 90 */
  expires_in_days?: number | null;
  name: string;
  roles: string[];
  scopes: string[];
};

export type ApiKeyIssued = {
  created_at: string;
  expires_at: string;
  id: string;
  /** Shown once. Store it in a secret manager. */
  key: string;
  name: string;
  owner_id: string;
  public_id: string;
  revoked_at: string | null;
  roles: string[];
  scopes: string[];
};

export type ApiKeyOut = {
  created_at: string;
  expires_at: string;
  id: string;
  name: string;
  owner_id: string;
  public_id: string;
  revoked_at: string | null;
  roles: string[];
  scopes: string[];
};

export type ApprovalOut = {
  approver_id: string;
  approver_roles: string[];
  created_at: string;
  version_id: string;
};

export type ArtifactGovIn = {
  derived_from_non_neural?: boolean | null;
  modalities?: Array<
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other'
  > | null;
  nervous_system?: 'central' | 'peripheral' | 'unknown' | null;
  reason?: string | null;
};

export type ArtifactOut = {
  id: string;
  name: string;
  sha256: string;
  size_bytes: number;
  step: string;
  visible_at: string;
};

export type ArtifactRef = {
  id: string;
  name: string;
  sha256: string;
  step: string;
};

export type AuditBatchOut = {
  batch_id: string;
  event_count: number;
  object_key: string;
  period_end: string;
  period_start: string;
  prev_id: string | null;
  seq: number;
};

export type AuditEventOut = {
  action: string | null;
  actor_id: string | null;
  actor_kind: string | null;
  auth_method: string | null;
  details: Record<string, unknown>;
  id: string;
  outcome: string;
  request_id: string | null;
  resource_id: string | null;
  resource_type: string | null;
  seq: number;
  ts: string;
  type: string;
};

export type BestOut = {
  mean: number;
  params: Record<string, unknown>;
  run_ids: string[];
  variant: number;
};

export type BulkIn = {
  /** only channels of this modality */
  modality?:
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other'
    | null;
  reason?: string | null;
  recording_ids: string[];
  set: GovValues;
};

export type CellOut = {
  artifact: ArtifactRef | null;
  /** {"<step>.<param>": value} */
  params: Record<string, unknown>;
  pipeline_ref: string;
  pipeline_version_id: string;
  /** the run's PROV activity node */
  prov_activity_id: string | null;
  /** PROV node of the artifact that carries the value */
  prov_node_id: string | null;
  recording_id: string;
  run_id: string;
  state: string;
  value: number | null;
  variant: number;
};

export type ChannelEdit = {
  derived_from_non_neural?: boolean | null;
  index: number;
  modality?:
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other'
    | null;
  nervous_system?: 'central' | 'peripheral' | 'unknown' | null;
};

export type ChannelEditsIn = {
  changes: ChannelEdit[];
  reason?: string | null;
};

export type ChannelIn = {
  derived_from_non_neural?: boolean | null;
  device_ref?: string | null;
  modality:
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other';
  name: string;
  nervous_system?: 'central' | 'peripheral' | 'unknown' | null;
  /** Hz */
  sampling_rate: number;
  units: string;
};

export type ChannelOut = {
  derived_from_non_neural: boolean;
  device_ref: string | null;
  index: number;
  modality: string;
  name: string;
  nervous_system: string;
  sampling_rate: number;
  units: string;
};

export type CompleteIn = {
  /** client SHA-256 (hex) */
  sha256: string;
};

export type ConfirmIn = {
  token: string;
};

export type ConfirmedOut = {
  status?: 'confirmed';
};

export type ConsentDocIn = {
  name: string;
  sha256: string;
  uri?: string | null;
  version: string;
};

export type ConsentDocOut = {
  created_at: string;
  id: string;
  name: string;
  sha256: string;
  uri: string | null;
  version: string;
};

export type ConsentIn = {
  document_id?: string | null;
  /** e.g. the object key of the signed form */
  evidence_ref?: string | null;
  jurisdiction_basis?: string | null;
  kind?: 'grant' | 'withdraw';
  scopes: Array<'collection' | 'processing' | 'sharing' | 'model_training' | 'commercial_use'>;
};

export type ConsentOut = {
  collector_id: string;
  document_id: string | null;
  document_sha256: string | null;
  evidence_ref: string | null;
  id: string;
  jurisdiction_basis: string | null;
  kind: string;
  prev_hash: string | null;
  record_hash: string;
  recorded_at: string;
  scopes: string[];
  seq: number;
  subject_id: string;
};

/** The declared deployment context. ``setting`` takes the values listed by */
export type ContextIn = {
  exception_id?: string | null;
  extra?: Record<string, string>;
  influences_behaviour?: boolean;
  jurisdiction: string;
  outputs?: 'labels' | 'coarse_scores' | 'logits' | 'embeddings';
  purpose: string;
  rate_limit_per_minute?: number;
  setting: string;
};

export type DatasetIn = {
  description?: string | null;
  name: string;
};

export type DatasetOut = {
  created_at: string;
  description: string | null;
  id: string;
  name: string;
  project_id: string;
};

export type DeletionOut = {
  aggregate_policy: string;
  certificate: Record<string, unknown> | null;
  duration_s: number | null;
  error: string | null;
  finished_at: string | null;
  id: string;
  requested_at: string;
  started_at: string | null;
  state: string;
  subject_id: string;
};

export type DeliveryOut = {
  attempts: number;
  created_at: string;
  delivered_at: string | null;
  event_id: string;
  event_type: string;
  id: string;
  last_error: string | null;
  last_status: number | null;
  next_attempt_at: string;
  state: 'pending' | 'delivered' | 'failed';
};

export type DeploymentIn = {
  context: ContextIn;
  version: number;
};

export type DeploymentOut = {
  context: Record<string, unknown>;
  created_at: string;
  effective_state: 'approved' | 'refused' | 'blocked';
  exception_id: string | null;
  id: string;
  jurisdiction: string;
  model_id: string;
  purpose: string;
  reasons: string[];
  requested_by: string;
  setting: string;
  state: 'approved' | 'refused';
  version: number;
  version_id: string;
};

export type DeviceIn = {
  name: string;
  /** Ed25519 public key, 32 bytes, base64 */
  public_key: string;
};

export type DeviceOut = {
  alg: string;
  created_at: string;
  id: string;
  name: string;
  public_key: string;
  revoked_at: string | null;
};

export type EarlyAccessIn = {
  email: string;
  organisation?: string | null;
  role: 'researcher' | 'engineer' | 'clinician' | 'founder' | 'student' | 'other';
  /** Honeypot: leave empty (hidden from people). */
  website?: string | null;
};

export type EvidenceIn = {
  /** provenance node of the dataset/model to document */
  node_id: string;
  /** release label */
  release?: string | null;
};

export type ExceptionIn = {
  basis: 'medical' | 'safety';
  evidence_ref: string;
  jurisdiction: string;
  justification: string;
  setting: 'workplace' | 'education';
};

export type ExceptionOut = {
  basis: string;
  created_at: string;
  evidence_ref: string;
  id: string;
  jurisdiction: string;
  justification: string;
  model_id: string;
  recorded_by: string;
  setting: string;
};

export type FactorOut = {
  name: string;
  values: unknown[];
};

export type FlagOut = {
  block_deployments: boolean;
  created_at: string;
  deletion_job_id: string;
  /** why the version is flagged: a training subject withdrew consent, or 'unverifiable lineage (uploaded weights)' (AppSec M3) */
  reason: string;
};

export type GovValues = {
  derived_from_non_neural?: boolean | null;
  modality?:
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other'
    | null;
  nervous_system?: 'central' | 'peripheral' | 'unknown' | null;
};

export type KeyVersionOut = {
  created_at: string;
  /** Set while a rotation overlap runs. */
  expires_at: string | null;
  version: number;
};

export type LevelOut = {
  mean: number | null;
  n: number;
  /** the runs this number is computed from */
  run_ids: string[];
  value: Record<string, unknown>;
};

export type LineageOut = {
  depth: number | null;
  direction: 'up' | 'down';
  edges: ProvEdgeOut[];
  nodes: ProvNodeOut[];
  root: string;
  /** True when the graph hit the node cap. */
  truncated: boolean;
};

export type ManifestIn = {
  excluded_subject_hashes?: string[];
  /** provenance entities the model was trained on */
  input_node_ids: string[];
  recipe?: string | null;
  /** SISA: subject hash -> shard */
  shards?: Record<string, number> | null;
  /** optional; must equal the subjects resolved from the lineage */
  subject_hashes?: string[] | null;
};

export type ManifestSummary = {
  n_excluded_subjects: number;
  n_inputs: number;
  n_shards: number | null;
  n_source_recordings: number;
  n_subjects: number;
  recipe: string | null;
  schema_id: string;
};

export type Measurement = {
  /** how it was measured */
  method: string;
  metric: string;
  notes?: string | null;
  /** evaluation split */
  split?: string | null;
  value: number;
};

export type MetricOut = {
  higher_is_better: boolean;
  key: string;
  name: string;
  step: string;
};

export type MetricSpec = {
  higher_is_better?: boolean;
  /** key in that step's run-record info */
  key?: string;
  /** pipeline step whose info holds it */
  step: string;
};

export type ModelCard = {
  card_schema?: 'nf.model-card/v1';
  contact?: string | null;
  evaluation?: Measurement[];
  inferences: Array<
    | 'emotion'
    | 'cognitive_state'
    | 'motor_intent'
    | 'sleep_stage'
    | 'seizure_risk'
    | 'artifact_detection'
    | 'sensitive_trait'
    | 'other'
  >;
  limitations: string;
  modalities: string[];
  privacy_risk?: PrivacyRisk | null;
  robustness: Robustness;
  summary: string;
  task: 'decoding' | 'classification' | 'regression' | 'detection' | 'representation' | 'other';
};

export type ModelDetailOut = {
  card: ModelCard;
  card_sha256: string;
  created_at: string;
  created_by: string;
  id: string;
  latest_version: VersionSummary | null;
  name: string;
  retrain_required: boolean;
  versions: VersionSummary[];
};

export type ModelIn = {
  card: ModelCard;
  name: string;
};

export type ModelLineageOut = {
  depth: number | null;
  direction: string;
  edges: Record<string, string>[];
  n_training_subjects: number;
  nodes: Record<string, unknown>[];
  root: string;
  truncated: boolean;
};

export type ModelOut = {
  card: ModelCard;
  card_sha256: string;
  created_at: string;
  created_by: string;
  id: string;
  latest_version: VersionSummary | null;
  name: string;
  retrain_required: boolean;
};

export type PartTargetOut = {
  auth: string;
  expires_at: string | null;
  method: string;
  part_number: number;
  url: string;
};

export type PipelineVersionOut = {
  created_at: string;
  created_by: string;
  /** pv:sha256:<64 hex>, the content address */
  id: string;
  name: string;
  /** name@version */
  ref: string;
  /** The published PipelineVersion document. */
  spec: Record<string, unknown>;
  version: string;
};

/** SEC-143: membership inference on a held-out split; required for publication. */
export type PrivacyRisk = {
  held_out_split: string;
  membership_inference: Measurement;
};

/** RFC 9457 problem details. Never contains stack traces, SQL, host names or credentials (SEC-079). */
export type Problem = {
  detail?: string;
  /** Validation errors (422): location and message, never the input. */
  errors?: {
    loc?: string[];
    msg?: string;
  }[];
  /** The request path. */
  instance?: string;
  /** Also in the X-Request-Id header. */
  request_id?: string;
  status: number;
  title: string;
  /** urn:nf:problem:<kind> or about:blank */
  type: string;
};

export type ProjectIn = {
  description?: string | null;
  name: string;
};

export type ProjectOut = {
  created_at: string;
  description: string | null;
  id: string;
  name: string;
};

export type ProvEdgeOut = {
  dst: string;
  rel:
    | 'used'
    | 'wasGeneratedBy'
    | 'wasDerivedFrom'
    | 'wasAttributedTo'
    | 'wasAssociatedWith'
    | 'wasInformedBy';
  src: string;
};

/** A PROV-JSON object (format=prov-json) or a list of OpenLineage RunEvents (openlineage). */
export type ProvExportOut = Record<string, unknown> | Record<string, unknown>[];

export type ProvNodeDetailOut = {
  edges_in: ProvEdgeOut[];
  edges_out: ProvEdgeOut[];
  node: ProvNodeOut;
};

export type ProvNodeOut = {
  attrs: Record<string, unknown>;
  batch_seq: number | null;
  content_hash: string | null;
  created_at: string;
  /** Hops from the root (lineage only). */
  depth?: number | null;
  id: string;
  kind: 'entity' | 'activity' | 'agent';
  node_hash: string;
  ref_id: string | null;
  /** raw_file, convert, recording, run, artifact, ... */
  type: string;
};

export type QuotaItem = {
  limit: number;
  used: number;
};

export type QuotasOut = {
  /** Queued + running runs. */
  active_runs: QuotaItem;
  /** Stored objects + uploads in flight. */
  storage_bytes: QuotaItem;
};

export type ReceivedPartOut = {
  part_number: number;
  sha256: string;
  size_bytes: number;
};

export type RecordingIn = {
  channels?: ChannelIn[];
  duration_s?: number | null;
  label: string;
  source_format?: string | null;
};

export type RecordingOut = {
  channels?: ChannelOut[];
  created_at: string;
  duration_s: number | null;
  id: string;
  label: string;
  session_id: string;
  source_format: string | null;
  state: string;
};

export type ReportOut = {
  best: BestOut | null;
  cells: CellOut[];
  complete: boolean;
  factors: FactorOut[];
  metric: MetricOut;
  pipeline: string;
  pipeline_version_id: string;
  prov_node_id: string | null;
  sensitivity: SensitivityOut[];
  state: string;
  sweep_id: string;
  variants: VariantSummary[];
};

export type RestrictionOut = {
  code: string;
  description: string;
};

export type RetrainIn = {
  recipe?: string | null;
};

export type RetrainOut = {
  error: string | null;
  finished_at: string | null;
  id: string;
  job_id: string | null;
  n_excluded_subjects: number;
  new_version_id: string | null;
  recipe: string | null;
  requested_at: string;
  requested_by: string;
  state: string;
  version_id: string;
};

/** SEC-145: evaluation on perturbed inputs (recorded, not claimed). */
export type Robustness = {
  /** a documented adversarial method (``method``) */
  adversarial: Measurement;
  channel_dropout: Measurement;
  noise: Measurement;
};

export type RotatedOut = {
  /** Older secrets keep verifying until then (both signatures are sent). */
  previous_valid_until: string;
  /** Shown once: the new signing secret. */
  signing_secret: string;
  version: number;
};

export type RunFinishedData = {
  finished_at: string | null;
  pipeline_ref: string;
  pipeline_version_id: string;
  /** PROV activity node of the run (succeeded runs). */
  prov_activity_id?: string | null;
  recording_id: string;
  run_id: string;
  state: 'succeeded' | 'failed' | 'cancelled';
};

/** Sent when a pipeline run reaches a terminal state. */
export type RunFinishedEvent = {
  api_version?: 'v1';
  created_at: string;
  data: RunFinishedData;
  /** Event ID; the same on every retry (deduplicate on it). */
  id: string;
  tenant_id: string;
  type: 'run.finished';
};

export type RunIn = {
  /** name@semver or pv:sha256:<64 hex> */
  pipeline: string;
  recording_id: string;
};

export type RunOut = {
  artifacts?: ArtifactOut[];
  attempt: number;
  cancel_requested?: boolean;
  created_at: string;
  error: string | null;
  finished_at: string | null;
  id: string;
  pipeline_ref: string;
  pipeline_version_id: string;
  prov_activity_id: string | null;
  prov_batch_id: string | null;
  record: Record<string, unknown>;
  recording_id: string;
  seed: number | null;
  started_at: string | null;
  state: string;
};

/** ``data`` of an ``event: run.state`` message. */
export type RunStateEvent = {
  attempt: number;
  error: string | null;
  finished_at: string | null;
  run_id: string;
  state: string;
};

/** One row of ``GET /v1/runs`` (no run record, no artifacts: open the run for those). */
export type RunSummaryOut = {
  attempt: number;
  created_at: string;
  created_by: string;
  error: string | null;
  finished_at: string | null;
  id: string;
  pipeline_ref: string;
  pipeline_version_id: string;
  recording_id: string;
  started_at: string | null;
  state: string;
};

export type SbomOut = {
  attached_at: string;
  attached_by: string;
  component_count: number;
  sha256: string;
  spec_version: string;
  version_id: string;
};

export type SensitivityOut = {
  factor: string;
  levels: LevelOut[];
  /** max - min of the level means */
  range: number | null;
};

export type SessionIn = {
  label: string;
  started_at?: string | null;
};

export type SessionOut = {
  created_at: string;
  id: string;
  label: string;
  started_at: string | null;
  subject_id: string;
};

export type StreamChannelIn = {
  derived_from_non_neural?: boolean | null;
  modality:
    | 'EEG'
    | 'iEEG'
    | 'ECoG'
    | 'SEEG'
    | 'LFP'
    | 'spikes'
    | 'MEG'
    | 'EMG'
    | 'ENG'
    | 'EOG'
    | 'ECG'
    | 'fNIRS'
    | 'other';
  name: string;
  nervous_system?: 'central' | 'peripheral' | 'unknown' | null;
  offset?: number;
  scale?: number;
  units: string;
};

export type StreamIn = {
  channels: StreamChannelIn[];
  device_id: string;
  dtype: 'int16' | 'int32' | 'float32' | 'float64';
  label: string;
  sfreq: number;
  synthetic?: boolean;
};

export type StreamOut = {
  /** SEC-093: acknowledgements carry no timing guarantee; never block acquisition on them */
  ack_timing?: string;
  /** Fully qualified gRPC service to stream chunks to. */
  grpc_service?: string;
  next_seq: number;
  recording_id: string;
  recording_state: string;
  stream_id: string;
  token_audience?: string;
};

export type SubjectIn = {
  /** Pseudonymous study code */
  label: string;
};

export type SubjectOut = {
  created_at: string;
  dataset_id: string;
  id: string;
  label: string;
};

export type SweepOut = {
  created_at: string;
  created_by: string;
  grid: Record<string, unknown[]>;
  id: string;
  metric: MetricSpec;
  name: string;
  pipeline: string;
  pipeline_version_id: string;
  prov_node_id: string | null;
  recording_ids: string[];
  run_ids: string[];
  run_states: Record<string, number>;
  /** queued | running | succeeded | partial | failed */
  state: string;
  variants: VariantOut[];
};

export type SweepRequest = {
  /** {"<step>.<param>": [value, ...]}; the cartesian product gives the variants */
  grid: Record<string, unknown[]>;
  metric: MetricSpec;
  name?: string | null;
  /** base PipelineVersion: name@semver or pv ID */
  pipeline: string;
  recording_ids: string[];
};

/** One row of ``GET /v1/sweeps`` (open the sweep for states, variants and run IDs). */
export type SweepSummaryOut = {
  created_at: string;
  created_by: string;
  id: string;
  n_runs: number;
  n_variants: number;
  name: string;
  pipeline_ref: string;
  pipeline_version_id: string;
  prov_node_id: string | null;
};

export type TenantPolicyIn = {
  aggregate_on_withdrawal: 'rerun' | 'tombstone';
  block_deployments_on_retrain?: boolean;
};

export type UploadIn = {
  filename: string;
  part_size?: number | null;
  session_id: string;
  size_bytes: number;
  /** SEC-071: true for synthetic or licence-checked public data (required outside prod and for synthetic-only tenants) */
  synthetic?: boolean;
};

export type UploadOut = {
  completed_at: string | null;
  created_at: string;
  dataset_id: string;
  error: string | null;
  filename: string;
  id: string;
  n_parts: number;
  part_size: number;
  parts: PartTargetOut[];
  received_parts: ReceivedPartOut[];
  recording_ids: string[];
  server_sha256: string | null;
  session_id: string;
  size_bytes: number;
  state: string;
  synthetic: boolean;
};

export type VariantOut = {
  /** {"<step>.<param>": value} */
  params: Record<string, unknown>;
  pipeline_ref: string;
  pipeline_version_id: string;
  variant: number;
};

export type VariantSummary = {
  mean: number | null;
  n: number;
  /** {"<step>.<param>": value} */
  params: Record<string, unknown>;
  pipeline_ref: string;
  pipeline_version_id: string;
  /** the runs this number is computed from */
  run_ids: string[];
  variant: number;
};

export type VersionIn = {
  code_commit: string;
  intended_use: string;
  parent_version?: number | null;
  /** pv:sha256:... ids or name@version */
  pipeline_version_ids?: string[];
  /** required: registering without a manifest fails */
  training_manifest?: ManifestIn | null;
  use_restrictions?: string[];
  weights: WeightsIn;
};

export type VersionOut = {
  code_commit: string;
  created_at: string;
  created_by: string;
  deployments_blocked: boolean;
  derived_object_id: string;
  id: string;
  intended_use: string;
  /** full manifest (hashed subject IDs) with include_manifest=true */
  manifest?: Record<string, unknown> | null;
  manifest_sha256: string;
  manifest_summary: ManifestSummary;
  model_id: string;
  parent_version: number | null;
  parent_version_id: string | null;
  pipeline_version_ids: string[];
  prov_node_id: string;
  published_at: string | null;
  recipe: string | null;
  retrain_required: boolean;
  taint: FlagOut[];
  use_restrictions: string[];
  version: number;
  visibility: string;
  weights_format: string;
  weights_sha256: string;
  /** platform: trained on the platform (exact lineage); upload: uploaded weights whose training lineage is the uploader's declaration (withdrawal propagation is conservative, four-eyes) */
  weights_source: 'platform' | 'upload';
};

export type VersionSummary = {
  created_at: string;
  deployments_blocked: boolean;
  id: string;
  retrain_required: boolean;
  version: number;
  visibility: string;
  /** platform: trained on the platform (exact lineage); upload: uploaded weights whose training lineage is the uploader's declaration (withdrawal propagation is conservative, four-eyes) */
  weights_source: 'platform' | 'upload';
};

export type VocabularyOut = {
  allowed_outputs: string[];
  outputs: string[];
  reason_codes: string[];
  restrictions: RestrictionOut[];
  settings: string[];
  statement: string;
};

export type WebhookIn = {
  description?: string | null;
  event_types: 'run.finished'[];
  /** https URL with a public DNS name (private, loopback, link-local and metadata addresses are refused, SEC-076) */
  url: string;
};

export type WebhookIssued = {
  created_at: string;
  created_by: string;
  description: string | null;
  disabled_at: string | null;
  event_types: string[];
  id: string;
  /** Signing keys currently valid. */
  key_versions: KeyVersionOut[];
  /** Shown once. HMAC-SHA-256 key for NF-Webhook-Signature (use its UTF-8 bytes). */
  signing_secret: string;
  url: string;
};

export type WebhookOut = {
  created_at: string;
  created_by: string;
  description: string | null;
  disabled_at: string | null;
  event_types: string[];
  id: string;
  /** Signing keys currently valid. */
  key_versions: KeyVersionOut[];
  url: string;
};

/** EITHER a model derived object produced by a platform training job OR inline uploaded */
export type WeightsIn = {
  data_base64?: string | null;
  derived_object_id?: string | null;
  format?: 'safetensors' | 'onnx' | null;
};

export type WhoAmIOut = {
  auth_method: string;
  id: string;
  /** user | api_key | device | service */
  kind: string;
  mfa_phishing_resistant: boolean;
  /** Effective roles: admin-class roles count only after a phishing-resistant login. */
  roles: string[];
  scopes: string[];
  tenant_id: string;
};

/** ``nf-window/1`` JSON form: header + ``data[channel][sample]`` in stored units */
export type WindowJsonOut = {
  byte_order: string;
  channels: string[];
  chunk_id: string;
  data: number[][];
  decimation: number;
  dtype: string;
  kind: 'samples' | 'mean' | 'min' | 'max';
  level: number;
  offset: number[];
  order: string;
  physical: string;
  scale: number[];
  sfreq: number;
  shape: number[];
  start_index: number;
  start_s: number;
  units: string[];
};

export type WithdrawalIn = {
  evidence_ref?: string | null;
};

export interface Operations {
  /** GET /v1/api-keys (action apikey:read) */
  listApiKeys: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: ApiKeyOut[];
  };
  /** POST /v1/api-keys (action apikey:create) */
  createApiKey: {
    path: never;
    query: never;
    body: ApiKeyIn;
    response: ApiKeyIssued;
  };
  /** DELETE /v1/api-keys/{key_id} (action apikey:revoke) */
  revokeApiKey: {
    path: {
      key_id: string;
    };
    query: never;
    body: never;
    response: unknown;
  };
  /** GET /v1/artifacts/{node_id}/governance (action governance:read) */
  getArtifactGovernance: {
    path: {
      node_id: string;
    };
    query: never;
    body: never;
    response: unknown;
  };
  /** PUT /v1/artifacts/{node_id}/governance (action governance:write) */
  putArtifactGovernance: {
    path: {
      node_id: string;
    };
    query: never;
    body: ArtifactGovIn;
    response: unknown;
  };
  /** GET /v1/audit/batches (action audit:read) */
  listAuditBatches: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: AuditBatchOut[];
  };
  /** GET /v1/audit/batches/{seq}/object (action audit:read) */
  getAuditBatchObject: {
    path: {
      seq: number;
    };
    query: never;
    body: never;
    response: unknown;
  };
  /** GET /v1/audit/events (action audit:read) */
  listAuditEvents: {
    path: never;
    query: {
      after_seq?: number;
      limit?: number;
    };
    body: never;
    response: AuditEventOut[];
  };
  /** GET /v1/classifications (action classification:read) */
  classifications: {
    path: never;
    query: {
      node_id?: string | null;
      recording_id?: string | null;
    };
    body: never;
    response: unknown;
  };
  /** GET /v1/consent-documents (action consent:read) */
  listConsentDocuments: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: ConsentDocOut[];
  };
  /** POST /v1/consent-documents (action consent:create) */
  createConsentDocument: {
    path: never;
    query: never;
    body: ConsentDocIn;
    response: ConsentDocOut;
  };
  /** GET /v1/datasets/{dataset_id} (action dataset:read) */
  getDataset: {
    path: {
      dataset_id: string;
    };
    query: never;
    body: never;
    response: DatasetOut;
  };
  /** GET /v1/datasets/{dataset_id}/subjects (action subject:read) */
  listSubjects: {
    path: {
      dataset_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: SubjectOut[];
  };
  /** POST /v1/datasets/{dataset_id}/subjects (action subject:create) */
  createSubject: {
    path: {
      dataset_id: string;
    };
    query: never;
    body: SubjectIn;
    response: SubjectOut;
  };
  /** POST /v1/datasets/{dataset_id}/uploads (action upload:create) */
  createUpload: {
    path: {
      dataset_id: string;
    };
    query: never;
    body: UploadIn;
    response: UploadOut;
  };
  /** GET /v1/deletion-jobs/{deletion_id} (action withdrawal:read) */
  getDeletion: {
    path: {
      deletion_id: string;
    };
    query: never;
    body: never;
    response: DeletionOut;
  };
  /** GET /v1/devices (action device:read) */
  listDevices: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: DeviceOut[];
  };
  /** POST /v1/devices (action device:create) */
  registerDevice: {
    path: never;
    query: never;
    body: DeviceIn;
    response: DeviceOut;
  };
  /** POST /v1/exports/fda-evidence (action evidence:export) */
  exportFdaEvidence: {
    path: never;
    query: never;
    body: EvidenceIn;
    response: unknown;
  };
  /** GET /v1/governance/certificate-key (action withdrawal:read) */
  certificateKey: {
    path: never;
    query: never;
    body: never;
    response: Record<string, string>;
  };
  /** POST /v1/governance/channels/bulk (action governance:write) */
  bulkEdit: {
    path: never;
    query: never;
    body: BulkIn;
    response: unknown;
  };
  /** GET /v1/governance/modality-defaults (action governance:read) */
  modalityDefaults: {
    path: never;
    query: never;
    body: never;
    response: Record<string, unknown>;
  };
  /** GET /v1/governance/tenant-policy (action governance:read) */
  getTenantPolicy: {
    path: never;
    query: never;
    body: never;
    response: Record<string, unknown>;
  };
  /** PUT /v1/governance/tenant-policy (action governance:admin) */
  putTenantPolicy: {
    path: never;
    query: never;
    body: TenantPolicyIn;
    response: Record<string, unknown>;
  };
  /** GET /v1/health (action public) */
  health: {
    path: never;
    query: never;
    body: never;
    response: Record<string, string>;
  };
  /** GET /v1/jurisdiction-rules (action classification:read) */
  jurisdictionRules: {
    path: never;
    query: never;
    body: never;
    response: Record<string, unknown>;
  };
  /** GET /v1/models (action model:read) */
  listModels: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: ModelOut[];
  };
  /** POST /v1/models (action model:create) */
  registerModel: {
    path: never;
    query: never;
    body: ModelIn;
    response: ModelDetailOut;
  };
  /** GET /v1/models/{model_id} (action model:read) */
  getModel: {
    path: {
      model_id: string;
    };
    query: never;
    body: never;
    response: ModelDetailOut;
  };
  /** GET /v1/models/{model_id}/deployments (action model:read) */
  listDeployments: {
    path: {
      model_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
      version?: number | null;
    };
    body: never;
    response: DeploymentOut[];
  };
  /** POST /v1/models/{model_id}/deployments (action model:deploy) */
  requestDeployment: {
    path: {
      model_id: string;
    };
    query: never;
    body: DeploymentIn;
    response: DeploymentOut;
  };
  /** GET /v1/models/{model_id}/retrains/{retrain_id} (action model:read) */
  getRetrain: {
    path: {
      model_id: string;
      retrain_id: string;
    };
    query: never;
    body: never;
    response: RetrainOut;
  };
  /** GET /v1/models/{model_id}/use-exceptions (action model:read) */
  listExceptions: {
    path: {
      model_id: string;
    };
    query: never;
    body: never;
    response: ExceptionOut[];
  };
  /** POST /v1/models/{model_id}/use-exceptions (action model:exception) */
  recordException: {
    path: {
      model_id: string;
    };
    query: never;
    body: ExceptionIn;
    response: ExceptionOut;
  };
  /** GET /v1/models/{model_id}/versions (action model:read) */
  listVersions: {
    path: {
      model_id: string;
    };
    query: never;
    body: never;
    response: VersionOut[];
  };
  /** POST /v1/models/{model_id}/versions (action model:train) */
  registerVersion: {
    path: {
      model_id: string;
    };
    query: never;
    body: VersionIn;
    response: VersionOut;
  };
  /** GET /v1/models/{model_id}/versions/{version} (action model:read) */
  getVersion: {
    path: {
      model_id: string;
      version: number;
    };
    query: {
      include_manifest?: boolean;
    };
    body: never;
    response: VersionOut;
  };
  /** POST /v1/models/{model_id}/versions/{version}/approvals (action model:approve) */
  approveVersion: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: never;
    response: ApprovalOut[];
  };
  /** GET /v1/models/{model_id}/versions/{version}/lineage (action model:read) */
  getVersionLineage: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: never;
    response: ModelLineageOut;
  };
  /** POST /v1/models/{model_id}/versions/{version}/publish (action model:publish) */
  publishVersion: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: never;
    response: VersionOut;
  };
  /** POST /v1/models/{model_id}/versions/{version}/retrain (action model:train) */
  requestRetrain: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: RetrainIn;
    response: RetrainOut;
  };
  /** PUT /v1/models/{model_id}/versions/{version}/sbom (action model:sbom-attach) */
  attachSbom: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: Record<string, unknown>;
    response: SbomOut;
  };
  /** GET /v1/models/{model_id}/versions/{version}/soup (action model:soup-export) */
  exportSoup: {
    path: {
      model_id: string;
      version: number;
    };
    query: never;
    body: never;
    response: unknown;
  };
  /** POST /v1/pipelines (action pipeline:create) */
  publishPipeline: {
    path: never;
    query: never;
    body: Record<string, unknown>;
    response: PipelineVersionOut;
  };
  /** GET /v1/pipelines/{pipeline_ref} (action pipeline:read) */
  getPipeline: {
    path: {
      pipeline_ref: string;
    };
    query: never;
    body: never;
    response: PipelineVersionOut;
  };
  /** GET /v1/projects (action project:read) */
  listProjects: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: ProjectOut[];
  };
  /** POST /v1/projects (action project:create) */
  createProject: {
    path: never;
    query: never;
    body: ProjectIn;
    response: ProjectOut;
  };
  /** GET /v1/projects/{project_id} (action project:read) */
  getProject: {
    path: {
      project_id: string;
    };
    query: never;
    body: never;
    response: ProjectOut;
  };
  /** GET /v1/projects/{project_id}/datasets (action dataset:read) */
  listDatasets: {
    path: {
      project_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: DatasetOut[];
  };
  /** POST /v1/projects/{project_id}/datasets (action dataset:create) */
  createDataset: {
    path: {
      project_id: string;
    };
    query: never;
    body: DatasetIn;
    response: DatasetOut;
  };
  /** GET /v1/provenance/{node_id} (action provenance:read) */
  getNode: {
    path: {
      node_id: string;
    };
    query: never;
    body: never;
    response: ProvNodeDetailOut;
  };
  /** GET /v1/provenance/{node_id}/export (action provenance:export) */
  exportLineage: {
    path: {
      node_id: string;
    };
    query: {
      depth?: number | null;
      direction?: 'up' | 'down';
      format: 'prov-json' | 'openlineage';
    };
    body: never;
    response: ProvExportOut;
  };
  /** GET /v1/provenance/{node_id}/lineage (action provenance:read) */
  getLineage: {
    path: {
      node_id: string;
    };
    query: {
      depth?: number | null;
      direction?: 'up' | 'down';
    };
    body: never;
    response: LineageOut;
  };
  /** GET /v1/quotas (action quota:read) */
  getQuotas: {
    path: never;
    query: never;
    body: never;
    response: QuotasOut;
  };
  /** GET /v1/recordings/{recording_id} (action recording:read) */
  getRecording: {
    path: {
      recording_id: string;
    };
    query: never;
    body: never;
    response: RecordingOut;
  };
  /** PATCH /v1/recordings/{recording_id}/channels (action governance:write) */
  editChannels: {
    path: {
      recording_id: string;
    };
    query: never;
    body: ChannelEditsIn;
    response: unknown;
  };
  /** GET /v1/recordings/{recording_id}/data (action signal:read) */
  readRecordingData: {
    path: {
      recording_id: string;
    };
    query: {
      channels?: string | null;
      end: number;
      format?: 'json' | 'binary';
      kind?: 'mean' | 'min' | 'max';
      level?: number;
      start: number;
    };
    body: never;
    response: WindowJsonOut;
  };
  /** GET /v1/registry/vocabulary (action model:read) */
  getVocabulary: {
    path: never;
    query: never;
    body: never;
    response: VocabularyOut;
  };
  /** GET /v1/runs (action run:read) */
  listRuns: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
      recording_id?: string | null;
      state?: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled' | null;
    };
    body: never;
    response: RunSummaryOut[];
  };
  /** POST /v1/runs (action run:create) */
  createRun: {
    path: never;
    query: never;
    body: RunIn;
    response: RunOut;
  };
  /** GET /v1/runs/{run_id} (action run:read) */
  getRun: {
    path: {
      run_id: string;
    };
    query: never;
    body: never;
    response: RunOut;
  };
  /** POST /v1/runs/{run_id}/cancel (action run:cancel) */
  cancelRun: {
    path: {
      run_id: string;
    };
    query: never;
    body: never;
    response: RunOut;
  };
  /** GET /v1/runs/{run_id}/events (action run:read) */
  streamRunEvents: {
    path: {
      run_id: string;
    };
    query: {
      wait_s?: number;
    };
    body: never;
    response: RunStateEvent;
  };
  /** GET /v1/sessions/{session_id} (action session:read) */
  getSession: {
    path: {
      session_id: string;
    };
    query: never;
    body: never;
    response: SessionOut;
  };
  /** GET /v1/sessions/{session_id}/recordings (action recording:read) */
  listRecordings: {
    path: {
      session_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: RecordingOut[];
  };
  /** POST /v1/sessions/{session_id}/recordings (action recording:create) */
  createRecording: {
    path: {
      session_id: string;
    };
    query: never;
    body: RecordingIn;
    response: RecordingOut;
  };
  /** POST /v1/sessions/{session_id}/streams (action stream:create) */
  openStream: {
    path: {
      session_id: string;
    };
    query: never;
    body: StreamIn;
    response: StreamOut;
  };
  /** GET /v1/subjects/{subject_id} (action subject:read) */
  getSubject: {
    path: {
      subject_id: string;
    };
    query: never;
    body: never;
    response: SubjectOut;
  };
  /** GET /v1/subjects/{subject_id}/consents (action consent:read) */
  getConsents: {
    path: {
      subject_id: string;
    };
    query: never;
    body: never;
    response: Record<string, unknown>;
  };
  /** POST /v1/subjects/{subject_id}/consents (action consent:create) */
  addConsent: {
    path: {
      subject_id: string;
    };
    query: never;
    body: ConsentIn;
    response: ConsentOut;
  };
  /** GET /v1/subjects/{subject_id}/sessions (action session:read) */
  listSessions: {
    path: {
      subject_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: SessionOut[];
  };
  /** POST /v1/subjects/{subject_id}/sessions (action session:create) */
  createSession: {
    path: {
      subject_id: string;
    };
    query: never;
    body: SessionIn;
    response: SessionOut;
  };
  /** POST /v1/subjects/{subject_id}/withdrawals (action withdrawal:create) */
  withdraw: {
    path: {
      subject_id: string;
    };
    query: never;
    body: WithdrawalIn;
    response: DeletionOut;
  };
  /** GET /v1/sweeps (action sweep:read) */
  listSweeps: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: SweepSummaryOut[];
  };
  /** POST /v1/sweeps (action sweep:create) */
  createSweep: {
    path: never;
    query: never;
    body: SweepRequest;
    response: SweepOut;
  };
  /** GET /v1/sweeps/{sweep_id} (action sweep:read) */
  getSweep: {
    path: {
      sweep_id: string;
    };
    query: never;
    body: never;
    response: SweepOut;
  };
  /** GET /v1/sweeps/{sweep_id}/report (action sweep:read) */
  getSweepReport: {
    path: {
      sweep_id: string;
    };
    query: never;
    body: never;
    response: ReportOut;
  };
  /** GET /v1/uploads/{upload_id} (action upload:read) */
  getUpload: {
    path: {
      upload_id: string;
    };
    query: never;
    body: never;
    response: UploadOut;
  };
  /** POST /v1/uploads/{upload_id}/complete (action upload:create) */
  completeUpload: {
    path: {
      upload_id: string;
    };
    query: never;
    body: CompleteIn;
    response: UploadOut;
  };
  /** PUT /v1/uploads/{upload_id}/parts/{part_number} (action upload:create) */
  putUploadPart: {
    path: {
      part_number: number;
      upload_id: string;
    };
    query: never;
    body: Blob;
    response: ReceivedPartOut;
  };
  /** GET /v1/webhooks (action webhook:read) */
  listWebhooks: {
    path: never;
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: WebhookOut[];
  };
  /** POST /v1/webhooks (action webhook:create) */
  createWebhook: {
    path: never;
    query: never;
    body: WebhookIn;
    response: WebhookIssued;
  };
  /** DELETE /v1/webhooks/{webhook_id} (action webhook:delete) */
  deleteWebhook: {
    path: {
      webhook_id: string;
    };
    query: never;
    body: never;
    response: unknown;
  };
  /** GET /v1/webhooks/{webhook_id} (action webhook:read) */
  getWebhook: {
    path: {
      webhook_id: string;
    };
    query: never;
    body: never;
    response: WebhookOut;
  };
  /** GET /v1/webhooks/{webhook_id}/deliveries (action webhook:read) */
  listWebhookDeliveries: {
    path: {
      webhook_id: string;
    };
    query: {
      limit?: number;
      offset?: number;
    };
    body: never;
    response: DeliveryOut[];
  };
  /** POST /v1/webhooks/{webhook_id}/rotate-secret (action webhook:update) */
  rotateWebhookSecret: {
    path: {
      webhook_id: string;
    };
    query: never;
    body: never;
    response: RotatedOut;
  };
  /** GET /v1/whoami (action self:read) */
  whoami: {
    path: never;
    query: never;
    body: never;
    response: WhoAmIOut;
  };
}

export type OperationName = keyof Operations;

export interface OperationMeta {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
  /** authz action from x-nf-action (null only for unmapped routes, which the server denies) */
  action: string | null;
  status: number;
  body: 'json' | 'binary' | null;
  responseTypes: readonly string[];
}

export const OPERATIONS: { readonly [K in OperationName]: OperationMeta } = {
  listApiKeys: {
    method: 'GET',
    path: '/v1/api-keys',
    action: 'apikey:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createApiKey: {
    method: 'POST',
    path: '/v1/api-keys',
    action: 'apikey:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  revokeApiKey: {
    method: 'DELETE',
    path: '/v1/api-keys/{key_id}',
    action: 'apikey:revoke',
    status: 204,
    body: null,
    responseTypes: [],
  },
  getArtifactGovernance: {
    method: 'GET',
    path: '/v1/artifacts/{node_id}/governance',
    action: 'governance:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  putArtifactGovernance: {
    method: 'PUT',
    path: '/v1/artifacts/{node_id}/governance',
    action: 'governance:write',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  listAuditBatches: {
    method: 'GET',
    path: '/v1/audit/batches',
    action: 'audit:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getAuditBatchObject: {
    method: 'GET',
    path: '/v1/audit/batches/{seq}/object',
    action: 'audit:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listAuditEvents: {
    method: 'GET',
    path: '/v1/audit/events',
    action: 'audit:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  classifications: {
    method: 'GET',
    path: '/v1/classifications',
    action: 'classification:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listConsentDocuments: {
    method: 'GET',
    path: '/v1/consent-documents',
    action: 'consent:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createConsentDocument: {
    method: 'POST',
    path: '/v1/consent-documents',
    action: 'consent:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getDataset: {
    method: 'GET',
    path: '/v1/datasets/{dataset_id}',
    action: 'dataset:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listSubjects: {
    method: 'GET',
    path: '/v1/datasets/{dataset_id}/subjects',
    action: 'subject:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createSubject: {
    method: 'POST',
    path: '/v1/datasets/{dataset_id}/subjects',
    action: 'subject:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  createUpload: {
    method: 'POST',
    path: '/v1/datasets/{dataset_id}/uploads',
    action: 'upload:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getDeletion: {
    method: 'GET',
    path: '/v1/deletion-jobs/{deletion_id}',
    action: 'withdrawal:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listDevices: {
    method: 'GET',
    path: '/v1/devices',
    action: 'device:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  registerDevice: {
    method: 'POST',
    path: '/v1/devices',
    action: 'device:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  exportFdaEvidence: {
    method: 'POST',
    path: '/v1/exports/fda-evidence',
    action: 'evidence:export',
    status: 200,
    body: 'json',
    responseTypes: ['application/zip'],
  },
  certificateKey: {
    method: 'GET',
    path: '/v1/governance/certificate-key',
    action: 'withdrawal:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  bulkEdit: {
    method: 'POST',
    path: '/v1/governance/channels/bulk',
    action: 'governance:write',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  modalityDefaults: {
    method: 'GET',
    path: '/v1/governance/modality-defaults',
    action: 'governance:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getTenantPolicy: {
    method: 'GET',
    path: '/v1/governance/tenant-policy',
    action: 'governance:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  putTenantPolicy: {
    method: 'PUT',
    path: '/v1/governance/tenant-policy',
    action: 'governance:admin',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  health: {
    method: 'GET',
    path: '/v1/health',
    action: 'public',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  jurisdictionRules: {
    method: 'GET',
    path: '/v1/jurisdiction-rules',
    action: 'classification:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listModels: {
    method: 'GET',
    path: '/v1/models',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  registerModel: {
    method: 'POST',
    path: '/v1/models',
    action: 'model:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getModel: {
    method: 'GET',
    path: '/v1/models/{model_id}',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listDeployments: {
    method: 'GET',
    path: '/v1/models/{model_id}/deployments',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  requestDeployment: {
    method: 'POST',
    path: '/v1/models/{model_id}/deployments',
    action: 'model:deploy',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getRetrain: {
    method: 'GET',
    path: '/v1/models/{model_id}/retrains/{retrain_id}',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listExceptions: {
    method: 'GET',
    path: '/v1/models/{model_id}/use-exceptions',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  recordException: {
    method: 'POST',
    path: '/v1/models/{model_id}/use-exceptions',
    action: 'model:exception',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  listVersions: {
    method: 'GET',
    path: '/v1/models/{model_id}/versions',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  registerVersion: {
    method: 'POST',
    path: '/v1/models/{model_id}/versions',
    action: 'model:train',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getVersion: {
    method: 'GET',
    path: '/v1/models/{model_id}/versions/{version}',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  approveVersion: {
    method: 'POST',
    path: '/v1/models/{model_id}/versions/{version}/approvals',
    action: 'model:approve',
    status: 201,
    body: null,
    responseTypes: ['application/json'],
  },
  getVersionLineage: {
    method: 'GET',
    path: '/v1/models/{model_id}/versions/{version}/lineage',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  publishVersion: {
    method: 'POST',
    path: '/v1/models/{model_id}/versions/{version}/publish',
    action: 'model:publish',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  requestRetrain: {
    method: 'POST',
    path: '/v1/models/{model_id}/versions/{version}/retrain',
    action: 'model:train',
    status: 202,
    body: 'json',
    responseTypes: ['application/json'],
  },
  attachSbom: {
    method: 'PUT',
    path: '/v1/models/{model_id}/versions/{version}/sbom',
    action: 'model:sbom-attach',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  exportSoup: {
    method: 'GET',
    path: '/v1/models/{model_id}/versions/{version}/soup',
    action: 'model:soup-export',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  publishPipeline: {
    method: 'POST',
    path: '/v1/pipelines',
    action: 'pipeline:create',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getPipeline: {
    method: 'GET',
    path: '/v1/pipelines/{pipeline_ref}',
    action: 'pipeline:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listProjects: {
    method: 'GET',
    path: '/v1/projects',
    action: 'project:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createProject: {
    method: 'POST',
    path: '/v1/projects',
    action: 'project:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getProject: {
    method: 'GET',
    path: '/v1/projects/{project_id}',
    action: 'project:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listDatasets: {
    method: 'GET',
    path: '/v1/projects/{project_id}/datasets',
    action: 'dataset:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createDataset: {
    method: 'POST',
    path: '/v1/projects/{project_id}/datasets',
    action: 'dataset:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getNode: {
    method: 'GET',
    path: '/v1/provenance/{node_id}',
    action: 'provenance:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  exportLineage: {
    method: 'GET',
    path: '/v1/provenance/{node_id}/export',
    action: 'provenance:export',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getLineage: {
    method: 'GET',
    path: '/v1/provenance/{node_id}/lineage',
    action: 'provenance:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getQuotas: {
    method: 'GET',
    path: '/v1/quotas',
    action: 'quota:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getRecording: {
    method: 'GET',
    path: '/v1/recordings/{recording_id}',
    action: 'recording:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  editChannels: {
    method: 'PATCH',
    path: '/v1/recordings/{recording_id}/channels',
    action: 'governance:write',
    status: 200,
    body: 'json',
    responseTypes: ['application/json'],
  },
  readRecordingData: {
    method: 'GET',
    path: '/v1/recordings/{recording_id}/data',
    action: 'signal:read',
    status: 200,
    body: null,
    responseTypes: ['application/json', 'application/vnd.nf.window.v1'],
  },
  getVocabulary: {
    method: 'GET',
    path: '/v1/registry/vocabulary',
    action: 'model:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listRuns: {
    method: 'GET',
    path: '/v1/runs',
    action: 'run:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createRun: {
    method: 'POST',
    path: '/v1/runs',
    action: 'run:create',
    status: 202,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getRun: {
    method: 'GET',
    path: '/v1/runs/{run_id}',
    action: 'run:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  cancelRun: {
    method: 'POST',
    path: '/v1/runs/{run_id}/cancel',
    action: 'run:cancel',
    status: 202,
    body: null,
    responseTypes: ['application/json'],
  },
  streamRunEvents: {
    method: 'GET',
    path: '/v1/runs/{run_id}/events',
    action: 'run:read',
    status: 200,
    body: null,
    responseTypes: ['text/event-stream'],
  },
  getSession: {
    method: 'GET',
    path: '/v1/sessions/{session_id}',
    action: 'session:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listRecordings: {
    method: 'GET',
    path: '/v1/sessions/{session_id}/recordings',
    action: 'recording:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createRecording: {
    method: 'POST',
    path: '/v1/sessions/{session_id}/recordings',
    action: 'recording:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  openStream: {
    method: 'POST',
    path: '/v1/sessions/{session_id}/streams',
    action: 'stream:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getSubject: {
    method: 'GET',
    path: '/v1/subjects/{subject_id}',
    action: 'subject:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getConsents: {
    method: 'GET',
    path: '/v1/subjects/{subject_id}/consents',
    action: 'consent:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  addConsent: {
    method: 'POST',
    path: '/v1/subjects/{subject_id}/consents',
    action: 'consent:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  listSessions: {
    method: 'GET',
    path: '/v1/subjects/{subject_id}/sessions',
    action: 'session:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createSession: {
    method: 'POST',
    path: '/v1/subjects/{subject_id}/sessions',
    action: 'session:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  withdraw: {
    method: 'POST',
    path: '/v1/subjects/{subject_id}/withdrawals',
    action: 'withdrawal:create',
    status: 202,
    body: 'json',
    responseTypes: ['application/json'],
  },
  listSweeps: {
    method: 'GET',
    path: '/v1/sweeps',
    action: 'sweep:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createSweep: {
    method: 'POST',
    path: '/v1/sweeps',
    action: 'sweep:create',
    status: 202,
    body: 'json',
    responseTypes: ['application/json'],
  },
  getSweep: {
    method: 'GET',
    path: '/v1/sweeps/{sweep_id}',
    action: 'sweep:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getSweepReport: {
    method: 'GET',
    path: '/v1/sweeps/{sweep_id}/report',
    action: 'sweep:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  getUpload: {
    method: 'GET',
    path: '/v1/uploads/{upload_id}',
    action: 'upload:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  completeUpload: {
    method: 'POST',
    path: '/v1/uploads/{upload_id}/complete',
    action: 'upload:create',
    status: 202,
    body: 'json',
    responseTypes: ['application/json'],
  },
  putUploadPart: {
    method: 'PUT',
    path: '/v1/uploads/{upload_id}/parts/{part_number}',
    action: 'upload:create',
    status: 200,
    body: 'binary',
    responseTypes: ['application/json'],
  },
  listWebhooks: {
    method: 'GET',
    path: '/v1/webhooks',
    action: 'webhook:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  createWebhook: {
    method: 'POST',
    path: '/v1/webhooks',
    action: 'webhook:create',
    status: 201,
    body: 'json',
    responseTypes: ['application/json'],
  },
  deleteWebhook: {
    method: 'DELETE',
    path: '/v1/webhooks/{webhook_id}',
    action: 'webhook:delete',
    status: 204,
    body: null,
    responseTypes: [],
  },
  getWebhook: {
    method: 'GET',
    path: '/v1/webhooks/{webhook_id}',
    action: 'webhook:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  listWebhookDeliveries: {
    method: 'GET',
    path: '/v1/webhooks/{webhook_id}/deliveries',
    action: 'webhook:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  rotateWebhookSecret: {
    method: 'POST',
    path: '/v1/webhooks/{webhook_id}/rotate-secret',
    action: 'webhook:update',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
  whoami: {
    method: 'GET',
    path: '/v1/whoami',
    action: 'self:read',
    status: 200,
    body: null,
    responseTypes: ['application/json'],
  },
};
