#!/usr/bin/env node
// Owner-facing matrix: for every URL in a built dist, the Content-Security-Policy and Cache-Control each host
// would send, computed from the same code the build uses (host-headers.mjs + csp-check.mjs exceptionsInUse).
// It reads dist only and writes Markdown to stdout; nothing is deployed.
// Usage: node scripts/headers-matrix.mjs <distDir>  > ../../docs/hive/HEADERS-MATRIX.md
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { HOSTS, hostHeadersForPath, hostRules } from '../host-headers.mjs';
import { csp, globalHeaders, resolveStage } from '../security-headers.mjs';
import { exceptionsInUse } from './csp-check.mjs';
import { sitePaths } from './postbuild.mjs';

/** Short label for a CSP value: "baseline", "arena" (baseline + route token) or "OTHER". */
function cspLabel(value, url) {
  if (value === csp()) return 'baseline';
  if (value === csp({ route: url })) return 'baseline + `wasm-unsafe-eval` (route exception)';
  return value ? '**OTHER: check**' : '**none**';
}

export function headersMatrix(dist, { stage = resolveStage() } = {}) {
  const paths = sitePaths(dist);
  const active = exceptionsInUse(dist);
  const urls = [...paths, '/_assets/<hashed>.js', '/does-not-exist'];
  const per = {};
  for (const host of HOSTS) {
    try {
      per[host] = { rules: hostRules(host, { stage, paths, active }) };
    } catch (e) {
      per[host] = { error: e.message };
    }
  }
  const out = [
    '# Headers matrix: what each host would send',
    '',
    `Generated by \`apps/web/scripts/headers-matrix.mjs\` from a local build (SITE_STAGE=${stage}). Nothing is deployed and no`,
    'host is chosen; `SITE_HOST=cloudflare` is only the build default. Regenerate after a build:',
    '`node apps/web/scripts/headers-matrix.mjs apps/web/dist/clinical > docs/hive/HEADERS-MATRIX.md`.',
    '',
    `Active SEC-150 exceptions in this build: ${active.length ? active.map((e) => e.route).join(', ') : 'none'}.`,
    '',
    '## Headers on every URL (both hosts)',
    '',
    '| Header | Value |',
    '|---|---|',
    ...Object.entries(globalHeaders(stage))
      .filter(([k]) => k !== 'Content-Security-Policy')
      .map(([k, v]) => `| ${k} | \`${v}\` |`),
    `| Content-Security-Policy (baseline) | \`${csp()}\` |`,
    '',
    '## Per URL',
    '',
    `| URL | ${HOSTS.map((h) => `${h}: CSP | ${h}: Cache-Control`).join(' | ')} |`,
    `|---|${HOSTS.map(() => '---|---').join('|')}|`,
  ];
  for (const u of urls) {
    const probe = u === '/_assets/<hashed>.js' ? '/_assets/example.AbCd1234.js' : u;
    const cells = HOSTS.map((h) => {
      if (per[h].error) return 'build fails | build fails';
      const hh = hostHeadersForPath(per[h].rules, probe);
      return `${cspLabel(hh['Content-Security-Policy'], probe)} | \`${hh['Cache-Control'] ?? '(host default)'}\``;
    });
    out.push(`| \`${u}\` | ${cells.join(' | ')} |`);
  }
  for (const h of HOSTS) if (per[h].error) out.push('', `**${h}:** ${per[h].error}`);
  out.push(
    '',
    'Notes: the route list is whatever the given dist contains, so it can lag main until the next build.',
    '`/does-not-exist` is the 404 response: it gets the `/*` security headers but no Cache-Control from us (host default).',
    'On Cloudflare, URLs without a trailing slash (e.g. `/security`)',
    'redirect to the slash form, and the redirect carries the `/*` headers; Netlify has a rule for both spellings.',
    'Verify the live values after a deploy with the checklist in `docs/hive/HOSTING-HEADERS.md`.',
    '',
  );
  return out.join('\n');
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  if (!process.argv[2]) {
    console.error('usage: node scripts/headers-matrix.mjs <distDir>');
    process.exit(2);
  }
  process.stdout.write(headersMatrix(resolve(process.argv[2])));
}
