"""Regenerate the committed gRPC/protobuf stubs from ``proto/ingest/v1/ingest.proto``.

The generated modules are committed (``_proto/``) so the server and the edge prototype run without
a build step; ``tests/ingest/test_stream_protocol.py`` regenerates them into a temp dir and fails if
they differ from the committed copies.

    .venv/Scripts/python -m nf_platform.ingest.stream.gen

Needs ``grpcio-tools`` (test extra). protoc emits ``import ingest_pb2``; it is rewritten to a
relative import so the stubs live inside this package.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROTO_ROOT = Path(__file__).resolve().parents[5] / "proto"
PROTO_FILE = Path("ingest") / "v1" / "ingest.proto"
OUT_DIR = Path(__file__).resolve().parent / "_proto"
HEADER = (
    "# Generated by nf_platform.ingest.stream.gen from proto/ingest/v1/ingest.proto. Do not edit.\n"
)


def generate(out_dir: Path = OUT_DIR, proto_root: Path = PROTO_ROOT) -> list[Path]:
    from grpc_tools import protoc  # noqa: PLC0415 (test/dev dependency only)

    out_dir.mkdir(parents=True, exist_ok=True)
    src_dir = proto_root / PROTO_FILE.parent
    args = [
        "protoc",
        f"-I{src_dir}",
        f"--python_out={out_dir}",
        f"--grpc_python_out={out_dir}",
        str(src_dir / PROTO_FILE.name),
    ]
    if protoc.main(args) != 0:
        raise RuntimeError("protoc failed")
    outs = [out_dir / "ingest_pb2.py", out_dir / "ingest_pb2_grpc.py"]
    for p in outs:
        text = p.read_text(encoding="utf-8").replace("\r\n", "\n")
        text = text.replace(
            "import ingest_pb2 as ingest__pb2", "from . import ingest_pb2 as ingest__pb2"
        )
        p.write_text(HEADER + text, encoding="utf-8", newline="\n")
    init = out_dir / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Generated stubs (see nf_platform.ingest.stream.gen)."""\n', newline="\n"
        )
    return outs


if __name__ == "__main__":
    for p in generate():
        sys.stdout.write(f"wrote {p}\n")
