# Customer-managed KMS keys (BLUEPRINT §8.1: KMS root -> tenant key -> per-subject data keys).
# The root key encrypts the buckets and the database. One KMS key per tenant (SEC-021) holds that
# tenant's KEK: the platform's AwsKms wraps per-subject data keys under the key named
# "<tenant_alias_prefix>nf/tenant/<tenant_id>" (nf_platform.storage.runtime.storage_from_env,
# NF_KMS_KEY_ALIAS_PREFIX). Per-subject data keys are generated by the application, not here.
# The application cannot create tenant keys: a tenant's id must be in tenant_ids (and applied)
# before its first upload, see infra/README.md "Tenant keys".
terraform {
  required_providers {
    aws = { source = "hashicorp/aws" }
  }
}

variable "name" {
  type        = string
  description = "Alias suffix, e.g. nf-dev"
}

variable "deletion_window_in_days" {
  type    = number
  default = 30
}

variable "tenant_ids" {
  type        = set(string)
  default     = []
  description = "Tenant UUIDs (tenant.id in the platform database) that get their own KEK"
  validation {
    condition = alltrue([
      for t in var.tenant_ids :
      can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", t))
    ])
    error_message = "tenant_ids must be lower-case UUIDs (the platform's tenant.id)."
  }
}

variable "tenant_alias_prefix" {
  type        = string
  default     = "alias/"
  description = "Must equal NF_KMS_KEY_ALIAS_PREFIX of the platform containers"
  validation {
    condition     = startswith(var.tenant_alias_prefix, "alias/")
    error_message = "tenant_alias_prefix must start with \"alias/\"."
  }
}

resource "aws_kms_key" "this" {
  description             = "${var.name} root key for envelope encryption"
  enable_key_rotation     = true
  deletion_window_in_days = var.deletion_window_in_days
}

resource "aws_kms_alias" "this" {
  name          = "alias/${var.name}"
  target_key_id = aws_kms_key.this.key_id
}

# Destroying a tenant key crypto-shreds ALL of that tenant's data (every wrapped DEK becomes
# undecryptable), so removing an id from tenant_ids fails the plan. Offboarding a tenant is a
# deliberate owner change (SEC-034), never a side effect of editing the list.
resource "aws_kms_key" "tenant" {
  for_each                = var.tenant_ids
  description             = "${var.name} KEK for tenant ${each.key}"
  enable_key_rotation     = true
  deletion_window_in_days = var.deletion_window_in_days

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_kms_alias" "tenant" {
  for_each      = var.tenant_ids
  name          = "${var.tenant_alias_prefix}nf/tenant/${each.key}"
  target_key_id = aws_kms_key.tenant[each.key].key_id
}

output "key_arn" {
  value = aws_kms_key.this.arn
}

output "key_id" {
  value = aws_kms_key.this.key_id
}

output "alias_name" {
  value = aws_kms_alias.this.name
}

output "tenant_key_arns" {
  value = { for t, k in aws_kms_key.tenant : t => k.arn }
}

output "tenant_alias_names" {
  value = { for t, a in aws_kms_alias.tenant : t => a.name }
}

output "tenant_alias_pattern" {
  description = "IAM kms:ResourceAliases pattern matching every tenant key"
  value       = "${var.tenant_alias_prefix}nf/tenant/*"
}
