# Generated by nf_platform.ingest.stream.gen from proto/ingest/v1/ingest.proto. Do not edit.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingest.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cingest.proto\x12\x14neuroforge.ingest.v1\"6\n\x0b\x43lockOffset\x12\x17\n\x0f\x63ollection_time\x18\x01 \x01(\x01\x12\x0e\n\x06offset\x18\x02 \x01(\x01\"<\n\x10LocalClockSample\x12\x10\n\x08lsl_time\x18\x01 \x01(\x01\x12\x16\n\x0emonotonic_time\x18\x02 \x01(\x01\"\xa2\x02\n\x05\x43hunk\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x11\n\tn_samples\x18\x03 \x01(\r\x12\x12\n\nn_channels\x18\x04 \x01(\r\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\x0f\n\x07samples\x18\x06 \x01(\x0c\x12\x16\n\x0elsl_timestamps\x18\x07 \x03(\x01\x12\x38\n\rclock_offsets\x18\x08 \x03(\x0b\x32!.neuroforge.ingest.v1.ClockOffset\x12;\n\x0blocal_clock\x18\t \x03(\x0b\x32&.neuroforge.ingest.v1.LocalClockSample\x12\x10\n\x08\x63hunk_id\x18\n \x01(\t\x12\x11\n\tsignature\x18\x0b \x01(\x0c\"g\n\tStreamAck\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08next_seq\x18\x02 \x01(\x04\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03 \x01(\r\x12\x12\n\nduplicates\x18\x04 \x01(\r\x12\x0f\n\x07suspect\x18\x05 \x01(\r\"\'\n\x12StreamStateRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\"(\n\x13\x46inishStreamRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\"e\n\x0bStreamState\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08next_seq\x18\x02 \x01(\x04\x12\x11\n\tn_samples\x18\x03 \x01(\x04\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0f\n\x07suspect\x18\x05 \x01(\x08\x32\x9c\x02\n\rIngestService\x12N\n\x0cStreamChunks\x12\x1b.neuroforge.ingest.v1.Chunk\x1a\x1f.neuroforge.ingest.v1.StreamAck(\x01\x12]\n\x0eGetStreamState\x12(.neuroforge.ingest.v1.StreamStateRequest\x1a!.neuroforge.ingest.v1.StreamState\x12\\\n\x0c\x46inishStream\x12).neuroforge.ingest.v1.FinishStreamRequest\x1a!.neuroforge.ingest.v1.StreamStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKOFFSET']._serialized_start=38
  _globals['_CLOCKOFFSET']._serialized_end=92
  _globals['_LOCALCLOCKSAMPLE']._serialized_start=94
  _globals['_LOCALCLOCKSAMPLE']._serialized_end=154
  _globals['_CHUNK']._serialized_start=157
  _globals['_CHUNK']._serialized_end=447
  _globals['_STREAMACK']._serialized_start=449
  _globals['_STREAMACK']._serialized_end=552
  _globals['_STREAMSTATEREQUEST']._serialized_start=554
  _globals['_STREAMSTATEREQUEST']._serialized_end=593
  _globals['_FINISHSTREAMREQUEST']._serialized_start=595
  _globals['_FINISHSTREAMREQUEST']._serialized_end=635
  _globals['_STREAMSTATE']._serialized_start=637
  _globals['_STREAMSTATE']._serialized_end=738
  _globals['_INGESTSERVICE']._serialized_start=741
  _globals['_INGESTSERVICE']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
