# Generated by nf_platform.ingest.stream.gen from proto/ingest/v1/ingest.proto. Do not edit.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingest_pb2 as ingest__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChunks = channel.stream_unary(
                '/neuroforge.ingest.v1.IngestService/StreamChunks',
                request_serializer=ingest__pb2.Chunk.SerializeToString,
                response_deserializer=ingest__pb2.StreamAck.FromString,
                _registered_method=True)
        self.GetStreamState = channel.unary_unary(
                '/neuroforge.ingest.v1.IngestService/GetStreamState',
                request_serializer=ingest__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=ingest__pb2.StreamState.FromString,
                _registered_method=True)
        self.FinishStream = channel.unary_unary(
                '/neuroforge.ingest.v1.IngestService/FinishStream',
                request_serializer=ingest__pb2.FinishStreamRequest.SerializeToString,
                response_deserializer=ingest__pb2.StreamState.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamChunks(self, request_iterator, context):
        """Client-stream of chunks in seq order starting at the server's next_seq (see GetStreamState).
        One acknowledgement when the client half-closes. The client may cut the stream at any time and
        resend from its write-ahead file; duplicates are harmless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamState(self, request, context):
        """The committed high-water mark of a stream (for resuming after a disconnect or restart).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishStream(self, request, context):
        """Marks the stream complete: the server builds the multiscale pyramid and stores the timing
        series next to the samples. No further chunks are accepted afterwards.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamChunks,
                    request_deserializer=ingest__pb2.Chunk.FromString,
                    response_serializer=ingest__pb2.StreamAck.SerializeToString,
            ),
            'GetStreamState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamState,
                    request_deserializer=ingest__pb2.StreamStateRequest.FromString,
                    response_serializer=ingest__pb2.StreamState.SerializeToString,
            ),
            'FinishStream': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishStream,
                    request_deserializer=ingest__pb2.FinishStreamRequest.FromString,
                    response_serializer=ingest__pb2.StreamState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neuroforge.ingest.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neuroforge.ingest.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/neuroforge.ingest.v1.IngestService/StreamChunks',
            ingest__pb2.Chunk.SerializeToString,
            ingest__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuroforge.ingest.v1.IngestService/GetStreamState',
            ingest__pb2.StreamStateRequest.SerializeToString,
            ingest__pb2.StreamState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuroforge.ingest.v1.IngestService/FinishStream',
            ingest__pb2.FinishStreamRequest.SerializeToString,
            ingest__pb2.StreamState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
