"""Generate spec/test-vectors/ids-v2.json (hashing spec v2, docs/spec/hashing.md §8-§10).

Run only when the v2 registrations change on purpose (the file is FROZEN once v2 is approved; a
change is a new spec version). The v1 files are generated by ``gen_vectors.py`` and never touched
here:
    .venv/Scripts/python.exe spec/reference/python/gen_vectors_v2.py
"""

from __future__ import annotations

import base64
from pathlib import Path
from typing import Any

import gen_vectors
import nf_canonical as nc
import nf_ids_v2 as v2

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "spec" / "test-vectors" / "ids-v2.json"

# RFC 8032 §7.1 TEST 1 secret key: a PUBLISHED test key, never a real one.
TEST_SECRET = bytes.fromhex("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60")
TEST_KEY_ID = "test-rfc8032-1"
TENANT = "00000000-0000-4000-8000-0000000000a1"
SUBJECT = "00000000-0000-4000-8000-0000000000b1"


def _sig(msg: bytes) -> str:
    return v2.ed25519_sign(TEST_SECRET, msg).hex()


def audit_chain() -> list[dict[str, Any]]:
    events = [
        [
            {
                "seq": 1,
                "id": "00000000-0000-4000-8000-000000000e01",
                "ts": "2026-09-26T10:15:00.123Z",
                "type": "auth",
                "action": "login",
                "outcome": "success",
                "actor": {"kind": "user", "id": "usr_1", "auth": "oidc"},
                "resource": {"type": "tenant", "id": TENANT},
                "request_id": "req-1",
                "details": {},
            },
            {
                "seq": 2,
                "id": "00000000-0000-4000-8000-000000000e02",
                "ts": "2026-09-26T10:40:00.000Z",
                "type": "data",
                "action": "recording.read",
                "outcome": "denied",
                "actor": {"kind": "api_key", "id": "key_1", "auth": "api_key"},
                "resource": {"type": "recording", "id": "rec-1"},
                "request_id": None,
                "details": {"reason": "consent", "note": "Café"},
            },
        ],
        [
            {
                "seq": 3,
                "id": "00000000-0000-4000-8000-000000000e03",
                "ts": "2026-09-26T11:05:00.500Z",
                "type": "admin",
                "action": "role.grant",
                "outcome": "success",
                "actor": {"kind": "user", "id": "usr_1", "auth": "oidc"},
                "resource": {"type": "user", "id": "usr_2"},
                "request_id": "req-3",
                "details": {"role": "analyst"},
            }
        ],
    ]
    out: list[dict[str, Any]] = []
    prev = None
    for seq, evs in enumerate(events):
        b = {
            "schema": v2.SCHEMA_AUDIT_BATCH,
            "scope": TENANT,
            "seq": seq,
            "prev": prev,
            "created_at": f"2026-09-26T1{seq + 1}:05:00.000Z",
            "period": {
                "start": f"2026-09-26T{10 + seq}:00:00.000Z",
                "end": f"2026-09-26T{11 + seq}:00:00.000Z",
            },
            "events": evs,
        }
        out.append(b)
        prev = v2.audit_batch_id(b)
    return out


# node_record(node_id, kind, type_, ref_id, content_hash, attrs) arguments (provenance/chain.py)
PROV_NODES: list[dict[str, Any]] = [
    {
        "name": "entity-full",
        "args": {
            "node_id": "00000000-0000-4000-8000-000000000c01",
            "kind": "entity",
            "type": "recording",
            "ref": "rec-1",
            "content": nc.blob_id(b"synthetic recording 1"),
            "attrs": {"modality": "eeg", "n_channels": 8, "label": "Å"},
        },
    },
    {
        "name": "activity-minimal",
        "args": {
            "node_id": "00000000-0000-4000-8000-000000000c02",
            "kind": "activity",
            "type": "run",
            "ref": None,
            "content": None,
            "attrs": None,
        },
    },
    {
        "name": "agent-empty-attrs-omitted",
        "args": {
            "node_id": "00000000-0000-4000-8000-000000000c03",
            "kind": "agent",
            "type": "pipeline_version",
            "ref": "pv:sha256:" + "0" * 64,
            "content": None,
            "attrs": {},
        },
    },
]


def prov_node_record(a: dict[str, Any]) -> dict[str, Any]:
    r: dict[str, Any] = {"type": a["kind"], "id": a["node_id"], "label": a["type"]}
    if a["ref"] is not None:
        r["ref"] = a["ref"]
    if a["content"] is not None:
        r["content"] = a["content"]
    if a["attrs"]:
        r["attrs"] = a["attrs"]
    return r


# record_doc(...) keyword arguments (governance/consent.py), minus tenant/seq/prev (the chain)
CONSENT_ENTRIES: list[dict[str, Any]] = [
    {
        "record_id": "00000000-0000-4000-8000-000000000d01",
        "subject_id": SUBJECT,
        "kind": "grant",
        "scopes": ["processing", "collection", "model_training", "collection"],
        "document_id": "00000000-0000-4000-8000-000000000f01",
        "document_sha256": nc.sha256_hex(b"consent form v1"),
        "basis": "GDPR Art. 9(2)(a)",
        "collector": "usr_1",
        "evidence": "paper-form-17",
        "recorded_at": "2026-09-26T09:00:00.000Z",
    },
    {
        "record_id": "00000000-0000-4000-8000-000000000d02",
        "subject_id": SUBJECT,
        "kind": "withdraw",
        "scopes": ["model_training"],
        "document_id": None,
        "document_sha256": None,
        "basis": None,
        "collector": "usr_2",
        "evidence": None,
        "recorded_at": "2026-09-26T09:30:00.250Z",
    },
]


def consent_record(e: dict[str, Any], seq: int, prev: str | None) -> dict[str, Any]:
    return {
        "schema": v2.SCHEMA_CONSENT_RECORD,
        "tenant": TENANT,
        "seq": seq,
        "prev": prev,
        "id": e["record_id"],
        "subject": e["subject_id"],
        "kind": e["kind"],
        "scopes": sorted(set(e["scopes"])),
        "document": None
        if e["document_id"] is None
        else {"id": e["document_id"], "sha256": e["document_sha256"]},
        "basis": e["basis"],
        "collector": e["collector"],
        "evidence": e["evidence"],
        "recorded_at": e["recorded_at"],
    }


# Rule.public() output (governance/rules.py): illustrative rules, NOT the repo's RuleSet.
RULES: list[dict[str, Any]] = [
    {
        "id": "xx-test-1",
        "jurisdiction": "XX",
        "title": "Illustrative neural-data rule",
        "instrument": "Test Act 2026",
        "status_text": "Test vector only; not a statement about any law.",
        "effective_date": "2026-01-01",
        "citation": {"section": "1(a)", "url": None},
        "predicate": {"attr": "nervous_system", "eq": True},
        "assumptions": [],
        "obligations": [{"id": "consent", "text": "Obtain opt-in consent.", "flag": "consent"}],
        "review_status": "draft",
        "review": None,
        "draft": True,
        "badge": "DRAFT: not counsel-reviewed",
        "notes": None,
    },
    {
        "id": "xx-test-2",
        "jurisdiction": "XX",
        "title": "Illustrative unverified rule",
        "instrument": "Test Act 2026",
        "status_text": "Test vector only.",
        "effective_date": None,
        "citation": {"section": "2"},
        "predicate": None,
        "assumptions": ["source not verified"],
        "obligations": [{"id": "notice", "text": "Give notice."}],
        "review_status": "unverified",
        "review": None,
        "draft": True,
        "badge": "UNVERIFIED: source not verified; draft, not counsel-reviewed",
        "notes": "Illustrative.",
    },
]


def stream_chunk_case() -> dict[str, Any]:
    samples = [0.5, -0.25, 1e-7, -0.0]  # float32, shape [n_samples=2, n_channels=2]
    data = nc.chunk_bytes("float32", samples)
    chunk = {
        "stream_id": "00000000-0000-4000-8000-0000000000c5",
        "seq": 7,
        "n_samples": 2,
        "n_channels": 2,
        "dtype": "float32",
        "samples": samples,
        "chunk_id": nc.chunk_id("float32", [2, 2], data),
        "lsl_timestamps": [1000.0, 1000.004],
        "clock_offsets": [[999.5, -0.0012]],
        "local_clock": [[1000.0, 52341.25], [1000.004, 52341.254]],
    }
    pre = v2.stream_chunk_preimage(chunk)
    return {
        "chunk": chunk,
        "timing_sha256": v2.stream_chunk_body(chunk)["timing_sha256"],
        "body": nc.canonicalize(v2.stream_chunk_body(chunk)).decode("utf-8"),
        "preimage_hex": pre.hex(),
        "signature_hex": _sig(pre),
    }


def device_token_case() -> dict[str, Any]:
    claims = {
        "aud": v2.DEVICE_TOKEN_AUDIENCE,
        "device_id": "dev-0001",
        "exp": 1790000300,
        "iat": 1790000000,
        "stream_id": "00000000-0000-4000-8000-0000000000c5",
        "tenant_id": TENANT,
    }
    pre = v2.device_token_preimage(claims)
    return {
        "claims": claims,
        "payload": v2.device_token_payload(claims).decode("utf-8"),
        "preimage_hex": pre.hex(),
        "signature_hex": _sig(pre),
        "token": v2.device_token(claims, TEST_SECRET),
    }


def anchor(schema: str, seq: int, head: str) -> dict[str, Any]:
    doc: dict[str, Any] = {
        "schema": schema,
        "tenant": TENANT,
        "seq": seq,
        "head": head,
        "anchored_at": "2026-09-27T00:00:00.000Z",
        "key_id": TEST_KEY_ID,
    }
    doc["sig"] = _sig(v2.anchor_signed_part(doc))
    return {"document": doc, "signed_part": v2.anchor_signed_part(doc).decode("utf-8")}


def certificate() -> dict[str, Any]:
    doc: dict[str, Any] = {
        "schema": v2.SCHEMA_DELETION_CERT,
        "certificate_id": "00000000-0000-4000-8000-0000000000d9",
        "tenant": TENANT,
        "subject_pseudonym": "P-017",
        "requested_at": "2026-09-26T12:00:00.123456+00:00",
        "completed_at": "2026-09-26T12:00:05.654321+00:00",
        "duration_s": 5.531,
        "objects_deleted": {"raw": 2, "derived": 1},
        "statement": "Illustrative test vector (fields abbreviated).",
    }
    part = v2.certificate_signed_part(doc)
    doc["signature"] = {
        "alg": "Ed25519",
        "key_id": TEST_KEY_ID,
        "value": base64.b64encode(v2.ed25519_sign(TEST_SECRET, part)).decode("ascii"),
    }
    return {"document": doc, "signed_part": part.decode("utf-8")}


# (tenant, subject) pairs for nf.training-subject.v1; the last one is upper-case input, folded.
TRAINING_SUBJECTS: list[tuple[str, str]] = [
    (TENANT, SUBJECT),
    (TENANT, "00000000-0000-4000-8000-0000000000b2"),
    ("00000000-0000-4000-8000-0000000000a2", SUBJECT),
    (TENANT.upper(), "00000000-0000-4000-8000-0000000000B2"),
]


def training_manifest_cases(pv_base: str) -> list[dict[str, Any]]:
    h1 = v2.training_subject_hash(TENANT, SUBJECT)
    h2 = v2.training_subject_hash(TENANT, "00000000-0000-4000-8000-0000000000b2")
    h3 = v2.training_subject_hash(TENANT, "00000000-0000-4000-8000-0000000000b3")
    base: dict[str, Any] = {
        "tenant_id": TENANT,
        "input_node_ids": [
            "00000000-0000-4000-8000-000000000c02",
            "00000000-0000-4000-8000-000000000c01",
        ],
        "subject_hashes": [h2, h1, h2],
        "n_source_recordings": 3,
        "shards": None,
        "excluded_subject_hashes": [],
        "pipeline_version_ids": [pv_base],
        "code_commit": "0" * 40,
        "recipe": None,
        "parent_version_id": None,
    }
    sisa = dict(
        base,
        subject_hashes=[h1],
        shards={h1: 0, h3: 1},
        excluded_subject_hashes=[h2],
        recipe="sisa",
        parent_version_id="00000000-0000-4000-8000-0000000000e9",
    )
    # duplicate (and upper-case) input ids: same set as "plain", so the same digest (§9.7). Listed
    # first so the frozen cases after it stay byte-identical in ids-v2.json (append-only change).
    dup = dict(
        base,
        input_node_ids=[
            "00000000-0000-4000-8000-000000000c02",
            "00000000-0000-4000-8000-000000000c01",
            "00000000-0000-4000-8000-000000000c02",
            "00000000-0000-4000-8000-000000000C01",
        ],
    )
    # AppSec M3 amendment (2026-09-26): ``weights_source``. Listed FIRST so every frozen case after
    # them stays byte-identical in ids-v2.json (a pure insertion, like duplicate-inputs above).
    ws_upload = dict(base, weights_source="upload")
    ws_platform = dict(sisa, weights_source="platform")
    out = []
    for name, args in [
        ("weights-source-upload", ws_upload),
        ("weights-source-platform", ws_platform),
        ("duplicate-inputs", dup),
        ("plain", base),
        ("sisa-retrain", sisa),
    ]:
        doc = v2.training_manifest(**args)
        out.append(
            {
                "name": name,
                "args": args,
                "manifest": doc,
                "payload": nc.canonicalize(doc).decode("utf-8"),
                "digest": v2.training_manifest_digest(doc),
            }
        )
    return out


def consent_noncanonical(canon: dict[str, Any]) -> dict[str, Any]:
    """§9.3: a record whose ``scopes`` are neither de-duplicated nor sorted hashes like its
    canonical form (the first chain record)."""
    rec = dict(canon, scopes=["processing", "collection", "model_training", "collection"])
    return {
        "note": "scopes are de-duplicated and sorted before hashing (= consent_record_chain[0])",
        "record": rec,
        "payload": nc.canonicalize(v2.canonical_consent_record(rec)).decode("utf-8"),
        "hash": v2.consent_record_hash(rec),
    }


def build() -> dict[str, Any]:
    v1_ids = gen_vectors.build()["ids.json"]
    pv_base = v1_ids["pipeline_version"][0]["id"]  # frozen v1 vector eeg-basic@1.2.0
    provb0 = v1_ids["prov_batch_chain"][0]["id"]

    audit = audit_chain()
    consent: list[dict[str, Any]] = []
    prev = None
    for seq, e in enumerate(CONSENT_ENTRIES):
        rec = consent_record(e, seq, prev)
        h = v2.consent_record_hash(rec)
        consent.append(
            {
                "args": e,
                "record": rec,
                "payload": nc.canonicalize(rec).decode("utf-8"),
                "hash": h,
            }
        )
        prev = h
    variants = [
        ("one-factor", {"filter.l_freq": 1.0}),
        ("two-factors", {"filter.l_freq": 0.5, "filter.method": "iir"}),
        ("factor-order-irrelevant", {"filter.method": "iir", "filter.l_freq": 0.5}),
    ]
    return {
        "spec": "docs/spec/hashing.md v2 §8-§10 (v1 vectors stay in ids.json, frozen)",
        "test_key": {
            "note": "RFC 8032 section 7.1 TEST 1 key pair: a published test key, never a real one",
            "key_id": TEST_KEY_ID,
            "secret_hex": TEST_SECRET.hex(),
            "public_hex": v2.ed25519_public_key(TEST_SECRET).hex(),
        },
        "audit_batch_chain": [
            {
                "batch": b,
                "payload": v2.audit_batch_payload(b).decode("utf-8"),
                "id": v2.audit_batch_id(b),
            }
            for b in audit
        ],
        "prov_node": [
            {
                "name": n["name"],
                "args": n["args"],
                "record": prov_node_record(n["args"]),
                "payload": nc.canonicalize(prov_node_record(n["args"])).decode("utf-8"),
                "hash": v2.prov_node_hash(prov_node_record(n["args"])),
            }
            for n in PROV_NODES
        ],
        "consent_record_chain": consent,
        "consent_record_noncanonical_scopes": consent_noncanonical(consent[0]["record"]),
        "ruleset": {
            "rules": RULES,
            "payload": nc.canonicalize(RULES).decode("utf-8"),
            "content_sha256": v2.ruleset_content_sha256(RULES),
        },
        "sweep_variant": [
            {
                "name": n,
                "base": pv_base,
                "params": p,
                "payload": nc.canonicalize({"base": pv_base, "params": p}).decode("utf-8"),
                "label": v2.sweep_variant_label(pv_base, p),
            }
            for n, p in variants
        ],
        "training_subject": [
            {
                "tenant_id": t,
                "subject_id": s,
                "preimage_hex": nc.tagged_preimage(
                    v2.TAG_TRAINING_SUBJECT,
                    v2.canonical_uuid(t).encode("ascii") + b"\x00" + v2.canonical_uuid(s).encode(),
                ).hex(),
                "hash": v2.training_subject_hash(t, s),
            }
            for t, s in TRAINING_SUBJECTS
        ],
        "training_manifest": training_manifest_cases(pv_base),
        "stream_chunk_signature": stream_chunk_case(),
        "device_token": device_token_case(),
        "provb_signature": {
            "batch_id": provb0,
            "message_hex": v2.provb_signature_message(provb0).hex(),
            "signature_hex": _sig(v2.provb_signature_message(provb0)),
        },
        "prov_anchor": anchor(v2.SCHEMA_PROV_ANCHOR, 0, provb0),
        "consent_anchor": anchor(v2.SCHEMA_CONSENT_ANCHOR, 1, consent[-1]["hash"]),
        "deletion_certificate": certificate(),
        "wal_aad": [
            {"stream_id": s, "seq": q, "aad_hex": v2.wal_aad(s, q).hex()}
            for s, q in [("00000000-0000-4000-8000-0000000000c5", 0), ("stream-é", 12345)]
        ],
    }


def dump_v2() -> str:
    return gen_vectors.dump(build())


def main() -> None:
    OUT.write_text(dump_v2(), encoding="ascii", newline="\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
