/*
 * neuroforge.h: stable C ABI of the NeuroForge Bio SDK core (nf-core). See docs/adr/0013-c-abi.md.
 *
 * Conventions
 * - Every fallible function returns nf_status; NF_OK is 0. Treat unknown non-zero codes as errors.
 * - On failure nf_last_error() holds a UTF-8 message for the calling thread (nf_last_error_detail()
 *   holds problem+json for NF_ERR_HTTP). Every call clears both on entry and again when it
 *   succeeds, so after NF_OK both are empty. Read them only after a non-OK status; the pointers
 *   are valid until the next nf_ call on the same thread.
 * - No call lets a Rust panic escape; an internal error returns NF_ERR_PANIC.
 * - Strings in: NUL-terminated UTF-8 (const char*). Documents and data in: (const uint8_t* ptr,
 *   size_t len); ptr may be NULL only when len is 0. Invalid UTF-8 is NF_ERR_INVALID_ARG.
 * - Results out: an nf_buf the caller releases with nf_buf_free (data[len] is always 0, so text
 *   results are C strings), or a caller buffer where stated (NF_ERR_BUFFER_TOO_SMALL reports the
 *   needed size). Outputs are written only on success.
 * - Handles: one constructor writes *out, one nf_<type>_free releases it (NULL is a no-op). Do not
 *   free a handle while another thread uses it.
 * - Thread safety is stated per type. Pure functions (hashing, IDs, verification) are thread-safe.
 * - Compatibility: the library is compatible with this header when
 *   (nf_abi_version() >> 16) == NF_ABI_VERSION_MAJOR and
 *   ((nf_abi_version() >> 8) & 0xff) >= NF_ABI_VERSION_MINOR.
 *
 * Data flows device -> SDK -> platform only. This ABI has no function that sends anything to
 * acquisition hardware or any other device (SEC-090/091).
 */

#ifndef NEUROFORGE_H
#define NEUROFORGE_H

/* Generated by cbindgen from bindings/c/src. Do not edit: run node bindings/c/tools/header.mjs */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// ABI major version: a change here breaks existing callers.
#define NF_ABI_VERSION_MAJOR 1

// ABI minor version: additions only.
#define NF_ABI_VERSION_MINOR 2

// ABI patch version: fixes without interface changes.
#define NF_ABI_VERSION_PATCH 1

// Fixed cap on one HTTP response: header names and values plus body together (64 MiB). Over it
// the request fails (CABI-M1 case 12). A transport that wants a lower limit (the engine default
// transports use 16 MiB) enforces it on its own side.
#define NF_MAX_RESPONSE_BYTES (64 << 20)

// Most response headers one reply may carry (`nf_http_reply_add_header`).
#define NF_MAX_RESPONSE_HEADERS 256

// Most bytes of header names plus values one reply may carry (256 KiB).
#define NF_MAX_RESPONSE_HEADER_BYTES (256 << 10)

// Largest reply accepted through `nf_reply_set` (1 MiB): ingest replies (StreamAck,
// StreamState), error messages and bearer tokens are all small. A larger reply is refused and
// the call fails as a transport error (CABI-M1 case 12: no unbounded buffering).
#define NF_MAX_REPLY_BYTES (1 << 20)

// An API client bound to one base URL. Opaque; free with `nf_api_client_free`.
typedef struct nf_api_client nf_api_client;

// A chunk read from the cache (decoded, little-endian). Opaque; free with `nf_chunk_free`.
typedef struct nf_chunk nf_chunk;

// The local content-addressed chunk cache. Opaque; free with `nf_chunk_cache_free`.
typedef struct nf_chunk_cache nf_chunk_cache;

// An Ed25519 device key. The secret never leaves the library. Opaque; thread-safe.
typedef struct nf_device_key nf_device_key;

// Response slot handed to the caller's HTTP transport. Opaque.
typedef struct nf_http_reply nf_http_reply;

// A 2xx response. Opaque; free with `nf_http_response_free`.
typedef struct nf_http_response nf_http_response;

// A local provenance chain. Opaque; free with `nf_prov_recorder_free`.
typedef struct nf_prov_recorder nf_prov_recorder;

// An open `nf-signal/1` recording (level 0). Opaque; free with `nf_recording_free`.
typedef struct nf_recording nf_recording;

// Reply slot handed to a callback. Opaque; fill it with `nf_reply_set` during the call only.
typedef struct nf_reply nf_reply;

// Uploads WAL chunks through a caller transport with batching, retries and device-token auth.
// Opaque.
typedef struct nf_sender nf_sender;

// Cuts pushed samples into signed chunks and appends them to the WAL. Opaque; locks
// internally (one producer thread is the intended use).
typedef struct nf_stream_writer nf_stream_writer;

// The encrypted on-disk write-ahead log of one stream. Opaque; thread-safe.
typedef struct nf_wal nf_wal;

// Result of every fallible call. Unknown non-zero values must be treated as errors (new codes
// may be added in a minor version).
typedef int32_t nf_status;

// A library-owned byte buffer. `data[len]` is always 0 (not counted in `len`), so text results
// are also C strings. Release with `nf_buf_free`. A zero-initialised `nf_buf` is empty.
typedef struct nf_buf {
    uint8_t *data;
    size_t len;
} nf_buf;

// Sample data types (hashing.md sec. 5.2). Values are stable across ABI versions.
typedef int32_t nf_dtype;

// One header or query pair (NUL-terminated UTF-8).
typedef struct nf_header {
    const char *name;
    const char *value;
} nf_header;

// A request handed to the caller's HTTP transport. Valid only during the callback.
typedef struct nf_http_request {
    const char *method;
    const char *url;
    const struct nf_header *headers;
    size_t n_headers;
    const uint8_t *body;
    size_t body_len;
    double timeout_s;
} nf_http_request;

// Perform one HTTP exchange. Return 0 after filling `reply` (status, headers, body) for any
// HTTP status, or non-zero for a transport failure (connection, TLS, timeout), with an
// optional UTF-8 message set via `nf_http_reply_set_body`.
typedef int32_t (*nf_http_send_fn)(void *user, const struct nf_http_request *request, struct nf_http_reply *reply);

// The caller's HTTP stack.
// Transport requirements (SEC-030, CABI-M1); a conforming transport MUST:
// 1. use TLS 1.3 only and refuse lower versions (plain http only to a loopback host);
// 2. verify the certificate chain and hostname on every connection (no accept-all handler);
// 3. never follow redirects (hand the 3xx back through the reply), and never send the
//    `authorization` header to any host other than the request URL's;
// 4. enforce `timeout_s` as the whole-request deadline;
// 5. never log, cache or persist `authorization`, request headers or bodies;
// 6. stop reading once the response passes `NF_MAX_RESPONSE_BYTES` or the header limits (the
//    `nf_http_reply_*` setters then fail, and so does the request).
//
// Thread contract: `send` runs on the thread that called
// `nf_api_client_request`, and may run concurrently from every thread that shares the client, so
// `send` and `user` must be thread-safe if the client is shared. It must not unwind, throw or
// longjmp.
typedef struct nf_http_transport {
    void *user;
    nf_http_send_fn send;
} nf_http_transport;

// Return a bearer token (`refresh` false) or a new one after a 401 (`refresh` true): set it with
// `nf_reply_set` and return 0, or return non-zero on failure.
typedef int32_t (*nf_token_fn)(void *user, bool refresh, struct nf_reply *reply);

// The caller's token store (API key, OIDC session, ...). Thread contract as for
// `nf_http_transport`: `token` may be called concurrently from every thread that shares the client
// (including a refresh on one thread while another reads), so it and `user` must be thread-safe.
typedef struct nf_token_source {
    void *user;
    nf_token_fn token;
} nf_token_source;

// The chunk fields a stream-chunk signature covers (hashing.md sec. 10.1). Pairs are flat
// `(a, b)` doubles: `clock_offsets` = (collection_time, offset), `local_clock` =
// (lsl_time, monotonic_time).
typedef struct nf_stream_chunk_fields {
    const char *stream_id;
    uint64_t seq;
    uint32_t n_samples;
    uint32_t n_channels;
    const char *chunk_id;
    const double *lsl_timestamps;
    size_t n_timestamps;
    const double *clock_offsets;
    size_t n_clock_offsets;
    const double *local_clock;
    size_t n_local_clock;
} nf_stream_chunk_fields;

// Level-0 facts of a recording.
typedef struct nf_recording_info {
    uint64_t n_samples;
    uint64_t n_channels;
    // Sampling frequency in Hz.
    double sfreq;
    // Stored dtype of the samples returned by `nf_recording_read`.
    nf_dtype dtype;
    // Whether `nf_recording_read_timestamps` has data.
    bool has_timestamps;
} nf_recording_info;

// Writer counters.
typedef struct nf_writer_stats {
    uint64_t chunks;
    uint64_t samples;
    // Largest WAL length seen after an append.
    uint64_t wal_peak;
} nf_writer_stats;

// Sender tuning. Start from `nf_sender_config_default`.
typedef struct nf_sender_config {
    // Most chunks per StreamChunks call (at least 1).
    size_t batch_max;
    // How long to wait for more chunks before sending a partial batch.
    double linger_s;
    // Per-call deadline.
    double call_timeout_s;
    // Retry backoff bounds.
    double backoff_min_s;
    double backoff_max_s;
} nf_sender_config;

// A unary ingest call: `request` is the serialized protobuf request, `authorization` the full
// metadata value (`NFDevice nfd1...`), `timeout_s` the deadline. Return 0 and set the serialized
// response with `nf_reply_set`, or return the gRPC status code (non-zero) and optionally set a
// message. Pointers are valid only during the call.
typedef int32_t (*nf_ingest_unary_fn)(void *user, const uint8_t *request, size_t request_len, const char *authorization, double timeout_s, struct nf_reply *reply);

// A borrowed byte range passed to callbacks (valid only during the call).
typedef struct nf_bytes {
    const uint8_t *data;
    size_t len;
} nf_bytes;

// The client-streaming ingest call: `chunks` are `n_chunks` serialized Chunk messages to send
// in order on one StreamChunks call; the reply is the serialized StreamAck.
typedef int32_t (*nf_ingest_chunks_fn)(void *user, const struct nf_bytes *chunks, size_t n_chunks, const char *authorization, double timeout_s, struct nf_reply *reply);

// The caller's gRPC transport for `nf.ingest.v1.IngestService`. `user` is passed through unchanged.
// Transport requirements (SEC-030, CABI-M1); a conforming transport MUST:
// 1. use TLS 1.3 only and refuse lower versions (plain http only to a loopback host);
// 2. verify the certificate chain and hostname on every connection (no accept-all handler);
// 3. never follow redirects (return the 3xx as the result), and never send `authorization`
//    to any host other than the one it was given;
// 4. enforce `timeout_s` as the whole-call deadline;
// 5. never log, cache or persist `authorization`, request headers or bodies;
// 6. keep the response within `NF_MAX_REPLY_BYTES` (larger replies fail the call).
//
// Thread contract: each callback runs on the thread that called `nf_sender_run`, `nf_sender_state`
// or `nf_sender_finish`. `nf_sender_run` calls them one at a time, but `nf_sender_state` or
// `nf_sender_finish` on another thread may call them concurrently with a running sender, so the
// callbacks and `user` must be thread-safe whenever you do that. Callbacks must not unwind, throw
// or longjmp, and must return within their `timeout_s`.
typedef struct nf_ingest_transport {
    void *user;
    nf_ingest_unary_fn get_stream_state;
    nf_ingest_chunks_fn stream_chunks;
    nf_ingest_unary_fn finish_stream;
} nf_ingest_transport;

// Server-side state of a stream. Free the strings with `nf_stream_state_free`.
typedef struct nf_stream_state {
    struct nf_buf stream_id;
    uint64_t next_seq;
    uint64_t n_samples;
    // For example `"open"` or `"finished"`.
    struct nf_buf state;
    bool suspect;
} nf_stream_state;

// Sender counters.
typedef struct nf_sender_stats {
    uint64_t calls;
    uint64_t chunks_acked;
    uint64_t rpc_errors;
    uint64_t next_seq_acked;
    // Whether the sender stopped on a fatal error (see `nf_sender_fatal_error`).
    bool fatal;
} nf_sender_stats;

#define NF_OK 0

// A required pointer argument was NULL.
#define NF_ERR_NULL_ARG 1

// An argument is malformed: invalid UTF-8, unknown dtype, bad shape, out-of-range value.
#define NF_ERR_INVALID_ARG 2

// A document cannot be canonicalised or breaks a hashing-spec rule (docs/spec/hashing.md).
#define NF_ERR_CANONICAL 3

// A hash chain, signature or token did not verify.
#define NF_ERR_VERIFY 4

// A filesystem operation failed.
#define NF_ERR_IO 5

// The requested item does not exist (missing file, cache miss, empty chain).
#define NF_ERR_NOT_FOUND 6

// A caller buffer is NULL or too small; the needed size was written to the size output.
#define NF_ERR_BUFFER_TOO_SMALL 7

// Stored data is corrupt or does not authenticate (WAL record, Zarr metadata).
#define NF_ERR_CORRUPT 8

// Not available on this platform or in this build (for example DPAPI outside Windows).
#define NF_ERR_UNSUPPORTED 9

// A caller transport reported a failure, or an RPC failed.
#define NF_ERR_TRANSPORT 10

// Authentication failed (token source error, or 401 after a refresh).
#define NF_ERR_AUTH 11

// The API answered with a non-2xx status; `nf_last_error_detail()` holds the problem+json.
#define NF_ERR_HTTP 12

// An internal error (a caught panic). Please report it.
#define NF_ERR_PANIC 13

#define NF_DTYPE_INT8 1

#define NF_DTYPE_UINT8 2

#define NF_DTYPE_INT16 3

#define NF_DTYPE_UINT16 4

#define NF_DTYPE_INT32 5

#define NF_DTYPE_UINT32 6

#define NF_DTYPE_INT64 7

#define NF_DTYPE_FLOAT32 8

#define NF_DTYPE_FLOAT64 9

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// ABI version of the loaded library: `major << 16 | minor << 8 | patch`. A caller built against
// this header is compatible when the majors are equal and the library minor is at least
// `NF_ABI_VERSION_MINOR`.
uint32_t nf_abi_version(void);

// Version of nf-core inside this library (static string, never freed).
const char *nf_core_version(void);

// Constant name of a status code (`"NF_OK"`, ...; `"NF_ERR_UNKNOWN"` otherwise). Static
// string, never freed.
const char *nf_status_name(nf_status status);

// Message of the last failed call on this thread, or `""`. Valid until the next `nf_` call on
// this thread; copy it if you need it longer.
const char *nf_last_error(void);

// Extra detail of the last failed call on this thread, or `""`: the problem+json body for
// `NF_ERR_HTTP`. Same lifetime as `nf_last_error()`.
const char *nf_last_error_detail(void);

// Release a buffer filled by the library and reset it to empty. NULL, an empty buffer and a
// buffer already freed are no-ops.
void nf_buf_free(struct nf_buf *buf);

// Name of a dtype (`"float32"`, ...), or NULL for an unknown code. Static string.
const char *nf_dtype_name(nf_dtype dtype);

// Size of one element in bytes, or 0 for an unknown code.
size_t nf_dtype_itemsize(nf_dtype dtype);

// Parse a dtype name (`"int16"`, ...) into `*out`.
nf_status nf_dtype_parse(const char *name, nf_dtype *out);

// Set the HTTP status of the reply.
nf_status nf_http_reply_set_status(struct nf_http_reply *reply, uint16_t status);

// Append one response header (copied). At most `NF_MAX_RESPONSE_HEADERS` headers and
// `NF_MAX_RESPONSE_HEADER_BYTES` of names plus values, and headers plus body together within
// `NF_MAX_RESPONSE_BYTES` whichever is set first: beyond that this returns
// `NF_ERR_INVALID_ARG` and the request fails as a transport error whatever the callback returns.
nf_status nf_http_reply_add_header(struct nf_http_reply *reply, const char *name, const char *value);

// Set the response body (copied), or the error message when the callback fails. The body may not
// make headers plus body exceed `NF_MAX_RESPONSE_BYTES`: above it this returns
// `NF_ERR_INVALID_ARG` and the request fails as a transport error whatever the callback returns.
// Setting the body again replaces it.
nf_status nf_http_reply_set_body(struct nf_http_reply *reply, const uint8_t *data, size_t len);

// Check a base URL against the SEC-030 policy (https, or http to a loopback host):
// `NF_OK` or `NF_ERR_INVALID_ARG`.
nf_status nf_check_base_url(const char *url);

// A client for `base_url` (checked with `nf_check_base_url`). `timeout_s` is passed to every
// transport call, `max_attempts` bounds retries (at least 1), `user_agent` may be NULL. The
// transport and token tables are copied; their `user` pointers must stay valid until
// `nf_api_client_free`.
nf_status nf_api_client_new(const char *base_url, const struct nf_http_transport *transport, const struct nf_token_source *tokens, double timeout_s, uint32_t max_attempts, const char *user_agent, struct nf_api_client **out_client);

// Free a client (NULL is a no-op).
void nf_api_client_free(struct nf_api_client *client);

// Send `method path?query` with auth and retries. `query` and `headers` are arrays of pairs
// (may be NULL when their count is 0); `body` may be NULL when `body_len` is 0. A 2xx answer
// yields `*out_response`; any other status is `NF_ERR_HTTP` with the problem+json in
// `nf_last_error_detail()`.
nf_status nf_api_client_request(const struct nf_api_client *client, const char *method, const char *path, const struct nf_header *query, size_t n_query, const struct nf_header *headers, size_t n_headers, const uint8_t *body, size_t body_len, struct nf_http_response **out_response);

// Free a response (NULL is a no-op).
void nf_http_response_free(struct nf_http_response *response);

// HTTP status (0 for NULL).
uint16_t nf_http_response_status(const struct nf_http_response *response);

// Number of response headers (0 for NULL).
size_t nf_http_response_header_count(const struct nf_http_response *response);

// Header `index`: `*out_name` and `*out_value` point into the response (valid until it is
// freed).
nf_status nf_http_response_header(const struct nf_http_response *response, size_t index, const char **out_name, const char **out_value);

// Response body, owned by the response; `*out_len` receives its length. NULL for NULL.
const uint8_t *nf_http_response_body(const struct nf_http_response *response, size_t *out_len);

// NF-CJSON v1 canonical bytes of a JSON document (hashing.md sec. 3).
nf_status nf_canonicalize(const uint8_t *json_text, size_t json_len, struct nf_buf *out_canonical);

// Canonical text of one number (hashing.md sec. 3.3). Non-finite values fail with
// `NF_ERR_CANONICAL`.
nf_status nf_format_number(double x, struct nf_buf *out_text);

// `blob:sha256:<hex>` of raw bytes (hashing.md sec. 5.1).
nf_status nf_blob_id(const uint8_t *data, size_t len, struct nf_buf *out_id);

// Streaming blob ID of a file, and its size in bytes (`out_size` may be NULL).
nf_status nf_blob_id_file(const char *path, struct nf_buf *out_id, uint64_t *out_size);

// `pv:sha256:<hex>` of a pipeline-version spec (hashing.md sec. 5.4).
nf_status nf_pipeline_version_id(const uint8_t *spec_json, size_t spec_len, struct nf_buf *out_id);

// `chunk:sha256:<hex>` of an array chunk (hashing.md sec. 5.2): `shape` has `rank` entries and
// `data` is `itemsize * prod(shape)` little-endian bytes in C order.
nf_status nf_chunk_id(nf_dtype dtype, const uint64_t *shape, size_t rank, const uint8_t *data, size_t data_len, struct nf_buf *out_id);

// `provb:sha256:<hex>` of one provenance batch (hashing.md sec. 5.3).
nf_status nf_prov_batch_id(const uint8_t *batch_json, size_t batch_len, struct nf_buf *out_id);

// Verify a provenance batch chain given as a JSON array of batches (hashing.md sec. 5.3). On
// success `out_ids` holds the batch IDs, one per line. A broken chain is `NF_ERR_VERIFY`.
nf_status nf_verify_prov_chain(const uint8_t *batches_json, size_t batches_len, struct nf_buf *out_ids);

// Whether `id` is a well-formed v1 ID (`blob|pv|chunk|provb:sha256:<64 hex>`). NULL or invalid
// UTF-8 is false.
bool nf_is_valid_id(const char *id);

// Whether `id` is a well-formed v2 ID (v1 kinds plus `auditb`).
bool nf_is_valid_id_v2(const char *id);

// `auditb:sha256:<hex>` of one audit batch (hashing.md sec. 9.1).
nf_status nf_audit_batch_id(const uint8_t *batch_json, size_t batch_len, struct nf_buf *out_id);

// Verify an audit batch chain (JSON array); IDs one per line. Broken chain: `NF_ERR_VERIFY`.
nf_status nf_verify_audit_chain(const uint8_t *batches_json, size_t batches_len, struct nf_buf *out_ids);

// Bare SHA-256 hex of a provenance node record (hashing.md sec. 9.2).
nf_status nf_prov_node_hash(const uint8_t *record_json, size_t record_len, struct nf_buf *out_hash);

// Bare SHA-256 hex of a consent record (hashing.md sec. 9.3; scopes are a set).
nf_status nf_consent_record_hash(const uint8_t *record_json, size_t record_len, struct nf_buf *out_hash);

// Verify a consent record chain (JSON array); hashes one per line. Broken: `NF_ERR_VERIFY`.
nf_status nf_verify_consent_chain(const uint8_t *records_json, size_t records_len, struct nf_buf *out_hashes);

// Bare SHA-256 hex of a jurisdiction ruleset's public rules (hashing.md sec. 9.4).
nf_status nf_ruleset_content_sha256(const uint8_t *rules_json, size_t rules_len, struct nf_buf *out_hash);

// Label of a parameter-sweep variant of `base_pv_id` (hashing.md sec. 9.5).
nf_status nf_sweep_variant_label(const char *base_pv_id, const uint8_t *params_json, size_t params_len, struct nf_buf *out_label);

// Bare SHA-256 hex identifying a training subject within a tenant (hashing.md sec. 9.6).
nf_status nf_training_subject_hash(const char *tenant_id, const char *subject_id, struct nf_buf *out_hash);

// Build a training manifest (hashing.md sec. 9.7) from a JSON object with the members
// `tenant_id`, `input_node_ids`, `subject_hashes`, `n_source_recordings`, `shards` (object or
// null), `excluded_subject_hashes`, `pipeline_version_ids`, `code_commit`, `recipe` and
// `parent_version_id` (string or null), and the optional `weights_source` (`"platform"` or
// `"upload"`; absent or null leaves the member out, so older manifests keep their digests).
// `out_manifest` receives the canonical JSON.
nf_status nf_training_manifest_build(const uint8_t *args_json, size_t args_len, struct nf_buf *out_manifest);

// Bare SHA-256 hex digest of a training manifest document (hashing.md sec. 9.7).
nf_status nf_training_manifest_digest(const uint8_t *manifest_json, size_t manifest_len, struct nf_buf *out_digest);

// Timing hash of a stream chunk (hashing.md sec. 10.1): `lsl_timestamps` has `n_timestamps`
// doubles; `clock_offsets` and `local_clock` are flat pairs (`2 * n` doubles each).
nf_status nf_timing_sha256(const double *lsl_timestamps, size_t n_timestamps, const double *clock_offsets, size_t n_clock_offsets, const double *local_clock, size_t n_local_clock, struct nf_buf *out_hash);

// Verify a stream-chunk signature (64 bytes) against a 32-byte Ed25519 public key.
// `*out_valid` is set; a bad signature is not an error.
nf_status nf_verify_stream_chunk(const struct nf_stream_chunk_fields *fields, const uint8_t *signature, size_t signature_len, const uint8_t *public_key, bool *out_valid);

// Parse and verify a device token (hashing.md sec. 10.2) at `now_unix_s`: signature, lifetime at
// most 600 s, validity within the 30 s leeway. On success `out_claims` (may be NULL) receives
// the canonical claims JSON; any failure is `NF_ERR_VERIFY`.
nf_status nf_verify_device_token(const char *token, const uint8_t *public_key, int64_t now_unix_s, struct nf_buf *out_claims);

// Verify an Ed25519 signature over a provenance batch ID (hashing.md sec. 10.3).
nf_status nf_verify_provb_signature(const char *batch_id, const uint8_t *signature, size_t signature_len, const uint8_t *public_key, bool *out_valid);

// Verify a signed provenance or consent chain-head anchor document (hashing.md sec. 10.4).
nf_status nf_verify_anchor(const uint8_t *anchor_json, size_t anchor_len, const uint8_t *public_key, bool *out_valid);

// Verify a signed deletion certificate document (hashing.md sec. 10.5).
nf_status nf_verify_certificate(const uint8_t *certificate_json, size_t certificate_len, const uint8_t *public_key, bool *out_valid);

// Open recording `recording_id` under the Zarr root directory `root` (read-only).
nf_status nf_recording_open(const char *root, const char *recording_id, struct nf_recording **out_recording);

// Free a recording (NULL is a no-op).
void nf_recording_free(struct nf_recording *recording);

// Level-0 facts of an open recording.
nf_status nf_recording_get_info(const struct nf_recording *recording, struct nf_recording_info *out_info);

// Name of channel `index` (0-based).
nf_status nf_recording_channel_name(const struct nf_recording *recording, uint64_t index, struct nf_buf *out_name);

// Unit of channel `index` (0-based), as stored (for example `"uV"`).
nf_status nf_recording_channel_unit(const struct nf_recording *recording, uint64_t index, struct nf_buf *out_unit);

// Read samples `[start, stop)` (clamped to `n_samples`) of all channels into a caller buffer:
// little-endian values of the recording dtype, row-major `[rows][n_channels]`.
// `*out_len` always receives the byte count needed; when `out` is NULL or `capacity` is
// smaller the call returns `NF_ERR_BUFFER_TOO_SMALL` without reading. An empty range needs no
// buffer: it returns `NF_OK` with `*out_len` = 0 even when `out` is NULL.
nf_status nf_recording_read(const struct nf_recording *recording, uint64_t start, uint64_t stop, uint8_t *out, size_t capacity, size_t *out_len);

// ABI 1.1. Read samples `[start, stop)` (clamped to `n_samples`) of all channels as physical
// values in double precision: `stored * scale + offset` per channel (zarr-layout.md), row-major
// `[rows][n_channels]`, in the units of `nf_recording_channel_unit`. `out` has room for
// `capacity` doubles; `*out_count` always receives the number of doubles needed, and a NULL or
// too small `out` returns `NF_ERR_BUFFER_TOO_SMALL` without reading; an empty range returns
// `NF_OK` with `*out_count` = 0 even when `out` is NULL. Use `nf_recording_read` for the exact
// stored values.
nf_status nf_recording_read_f64(const struct nf_recording *recording, uint64_t start, uint64_t stop, double *out, size_t capacity, size_t *out_count);

// Read timestamps `[start, stop)` (clamped) into `out` (room for `capacity` doubles): the
// original per-sample times in float64 seconds, as recorded (for streamed data the sender's LSL
// clock; for converted files the source format's clock). They are not Unix time unless the
// source used it; the recording's wall-clock anchor is its `start_time` attribute.
// `*out_count` receives the number of timestamps needed. `NF_ERR_NOT_FOUND` when the recording
// has no timestamps; `NF_ERR_BUFFER_TOO_SMALL` as for `nf_recording_read`.
nf_status nf_recording_read_timestamps(const struct nf_recording *recording, uint64_t start, uint64_t stop, double *out, size_t capacity, size_t *out_count);

// Open the cache rooted at `root` (created if missing). `max_bytes` bounds its size; this ABI
// only reads, so the bound matters only to other writers of the same directory.
nf_status nf_chunk_cache_open(const char *root, uint64_t max_bytes, struct nf_chunk_cache **out_cache);

// Free a cache handle (NULL is a no-op). Cached files are kept.
void nf_chunk_cache_free(struct nf_chunk_cache *cache);

// Fetch chunk `chunk_id` and verify its hash. `NF_ERR_NOT_FOUND` on a miss; an entry that fails
// verification is removed from the cache and also reported as `NF_ERR_NOT_FOUND`.
nf_status nf_chunk_cache_get(const struct nf_chunk_cache *cache, const char *chunk_id, struct nf_chunk **out_chunk);

// Total bytes currently cached.
nf_status nf_chunk_cache_size(const struct nf_chunk_cache *cache, uint64_t *out_bytes);

// Free a chunk (NULL is a no-op).
void nf_chunk_free(struct nf_chunk *chunk);

// Dtype of a chunk (0 for NULL).
nf_dtype nf_chunk_dtype(const struct nf_chunk *chunk);

// Rank of a chunk (0 for NULL).
size_t nf_chunk_rank(const struct nf_chunk *chunk);

// Shape of a chunk (`rank` entries), owned by the chunk (NULL for NULL).
const uint64_t *nf_chunk_shape(const struct nf_chunk *chunk);

// Decoded little-endian bytes of a chunk, owned by the chunk; `*out_len` receives the length.
// NULL (and 0) for a NULL chunk.
const uint8_t *nf_chunk_data(const struct nf_chunk *chunk, size_t *out_len);

// Open (or create) chain `chain` in directory `dir` and verify it. A chain that does not verify
// is `NF_ERR_VERIFY`.
nf_status nf_prov_recorder_open(const char *dir, const char *chain, struct nf_prov_recorder **out_recorder);

// Free a recorder (NULL is a no-op). The chain stays on disk.
void nf_prov_recorder_free(struct nf_prov_recorder *recorder);

// Append one batch. `records_json` is a JSON array of PROV records
// (`{"type":"entity"|"activity"|"agent","id","label"[,"content"]}` or
// `{"type":"edge","rel","from","to"}`). `out_seq` (may be NULL) receives the batch sequence
// number and `out_id` (may be NULL) its `provb:` ID.
nf_status nf_prov_recorder_record(const struct nf_prov_recorder *recorder, const uint8_t *records_json, size_t records_len, uint64_t *out_seq, struct nf_buf *out_id);

// Number of batches in the chain.
nf_status nf_prov_recorder_len(const struct nf_prov_recorder *recorder, size_t *out_len);

// Sequence number and ID of the newest batch; `NF_ERR_NOT_FOUND` for an empty chain.
nf_status nf_prov_recorder_head(const struct nf_prov_recorder *recorder, uint64_t *out_seq, struct nf_buf *out_id);

// Number of batches not yet marked synced.
nf_status nf_prov_recorder_pending_count(const struct nf_prov_recorder *recorder, size_t *out_count);

// Pending batch `index` (0 = oldest unsynced): sequence number, ID, and the canonical batch
// bytes to upload (`out_canonical` may be NULL).
nf_status nf_prov_recorder_pending(const struct nf_prov_recorder *recorder, size_t index, uint64_t *out_seq, struct nf_buf *out_id, struct nf_buf *out_canonical);

// Mark every batch up to and including `seq` as synced (persisted).
nf_status nf_prov_recorder_mark_synced(const struct nf_prov_recorder *recorder, uint64_t seq);

// Generate a new random device key.
nf_status nf_device_key_generate(struct nf_device_key **out_key);

// Import an existing 32-byte Ed25519 seed (for keys held in an OS keystore). There is no way to
// export it again.
nf_status nf_device_key_from_seed(const uint8_t *seed, size_t seed_len, struct nf_device_key **out_key);

// Windows: load the key sealed with DPAPI at `path`, or create and seal a new one there.
// Elsewhere: `NF_ERR_UNSUPPORTED`. Note (NR-L6): the seal uses DPAPI without extra entropy, so any
// process running as the same Windows user can unseal the key; prefer an OS keystore seed via
// `nf_device_key_from_seed` where the platform offers one.
nf_status nf_device_key_open_sealed(const char *path, struct nf_device_key **out_key);

// Free a device key (NULL is a no-op). Writers and senders keep their own reference.
void nf_device_key_free(struct nf_device_key *key);

// Copy the 32-byte public key into `out_public_key` (room for 32 bytes).
nf_status nf_device_key_public_key(const struct nf_device_key *key, uint8_t *out_public_key);

// A device token (`nfd1.<payload>.<sig>`, hashing.md sec. 10.2) for `tenant_id`/`device_id`/
// `stream_id`, valid `lifetime_s` seconds (at most 600) from now.
nf_status nf_device_key_token(const struct nf_device_key *key, const char *tenant_id, const char *device_id, const char *stream_id, uint64_t lifetime_s, struct nf_buf *out_token);

// Open (or create) the WAL of `stream_id` in `dir` with a persistent key. Key source, first
// match wins: `key32` (32 bytes from an OS keystore: Windows DPAPI/Credential Manager, macOS
// Keychain, Linux libsecret, Android Keystore), then `dpapi_key_path` (Windows only: a
// DPAPI-sealed file created on first use; DPAPI without extra entropy can be unsealed by any
// process of the same Windows user, tracked as NR-L6). Passing neither is `NF_ERR_INVALID_ARG`
// since ABI 1.2: a WAL whose key dies with the process silently loses every unsent record on a
// crash (CABI-L3); use `nf_wal_open_ephemeral` to ask for that explicitly. `fsync` makes every
// append durable.
nf_status nf_wal_open(const char *dir, const char *stream_id, const uint8_t *key32, const char *dpapi_key_path, bool fsync, struct nf_wal **out_wal);

// FOR TESTS AND THROWAWAY SESSIONS ONLY: records are unreadable after the process ends.
// ABI 1.2. Opens (or creates) the WAL of `stream_id` in `dir` with a random in-memory key, so
// unsent data is lost on a crash or restart. Wrappers must expose this only under an explicit
// testing name, never as a default or an overload of the normal open (nfb-security, CABI-L3).
nf_status nf_wal_open_ephemeral(const char *dir, const char *stream_id, bool fsync, struct nf_wal **out_wal);

// Free a WAL handle (NULL is a no-op). Records stay on disk; writers and senders keep their own
// reference.
void nf_wal_free(struct nf_wal *wal);

// Number of records waiting in the WAL (not yet acknowledged by the platform).
nf_status nf_wal_len(const struct nf_wal *wal, size_t *out_len);

// A writer for `stream_id`: `dtype` must be int16, int32, float32 or float64; `chunk_samples`
// samples per chunk. Each chunk is signed once (Ed25519), so keep a chunk at **20 ms or longer**
// (`chunk_samples >= 0.02 * sampling rate`, e.g. 20 at 1 kHz, 600 at 30 kHz): below that the
// signature dominates the per-chunk cost on the device and on the verifying server (bci-hive
// 013). The ABI cannot check this yet because it is not given the sampling rate.
nf_status nf_stream_writer_new(const char *stream_id, nf_dtype dtype, uint32_t n_channels, uint32_t chunk_samples, const struct nf_device_key *key, const struct nf_wal *wal, struct nf_stream_writer **out_writer);

// Free a writer (NULL is a no-op). Buffered samples that were not flushed are dropped.
void nf_stream_writer_free(struct nf_stream_writer *writer);

// Push `n_timestamps` samples: `samples` holds `n_timestamps * n_channels` little-endian values
// of the writer dtype in row-major order (`samples_len` bytes), `timestamps` one finite time per
// sample: float64 seconds on the sender's LSL clock (`lsl_local_clock()`, an arbitrary
// host-local origin, not Unix time), stored and uploaded as given, never rewritten. `out_chunks`
// (may be NULL) receives how many full chunks were written.
nf_status nf_stream_writer_push(const struct nf_stream_writer *writer, const uint8_t *samples, size_t samples_len, const double *timestamps, size_t n_timestamps, size_t *out_chunks);

// Record an LSL clock offset measurement (`time_correction`): `offset` = remote clock - local
// clock at `collection_time`, both float64 seconds on the local LSL clock. It travels with the
// next chunk.
nf_status nf_stream_writer_add_clock_offset(const struct nf_stream_writer *writer, double collection_time, double offset);

// Record the local LSL clock and the operating system's monotonic clock read at the same instant
// (both float64 seconds); it travels with the next chunk and lets the platform relate the two.
nf_status nf_stream_writer_add_local_clock(const struct nf_stream_writer *writer, double lsl_time, double monotonic_time);

// Write the buffered partial chunk (end of acquisition). `out_wrote` (may be NULL) tells
// whether there was one.
nf_status nf_stream_writer_flush(const struct nf_stream_writer *writer, bool *out_wrote);

// Sequence number the next chunk will get.
nf_status nf_stream_writer_next_seq(const struct nf_stream_writer *writer, uint64_t *out_seq);

// Samples pushed but not yet in a chunk.
nf_status nf_stream_writer_buffered_samples(const struct nf_stream_writer *writer, size_t *out_samples);

// Writer counters.
nf_status nf_stream_writer_get_stats(const struct nf_stream_writer *writer, struct nf_writer_stats *out_stats);

// Store a copy of `data` as the callback's reply: the response message bytes when the callback
// returns 0, or a UTF-8 error message otherwise. More than `NF_MAX_REPLY_BYTES` is refused with
// `NF_ERR_INVALID_ARG`, and the call then fails as a transport error whatever the callback
// returns.
nf_status nf_reply_set(struct nf_reply *reply, const uint8_t *data, size_t len);

// Defaults: batch_max 50, linger 0.2 s, call timeout 10 s, backoff 0.05..1 s.
nf_status nf_sender_config_default(struct nf_sender_config *out_config);

// A sender for one stream. `config` may be NULL for the defaults.
nf_status nf_sender_new(const char *tenant_id, const char *device_id, const char *stream_id, const struct nf_device_key *key, const struct nf_wal *wal, const struct nf_sender_config *config, struct nf_sender **out_sender);

// Free a sender (NULL is a no-op). Must not be called while `nf_sender_run` is running.
void nf_sender_free(struct nf_sender *sender);

// Upload WAL chunks until `nf_sender_stop` is called or a fatal error occurs (check
// `nf_sender_get_stats`). Blocks the calling thread; the transport callbacks run on it. Other
// threads may call `nf_sender_stop` and `nf_sender_get_stats` meanwhile. Only one
// `nf_sender_run` or `nf_sender_finish` may be active per sender: a second one returns
// `NF_ERR_INVALID_ARG` at once.
nf_status nf_sender_run(const struct nf_sender *sender, const struct nf_ingest_transport *transport);

// Ask a running `nf_sender_run` to return (thread-safe).
nf_status nf_sender_stop(const struct nf_sender *sender);

// Clear a previous stop so `nf_sender_run` can be called again.
nf_status nf_sender_reset(const struct nf_sender *sender);

// Ask the platform for the stream's state (GetStreamState). Failures are `NF_ERR_TRANSPORT`.
nf_status nf_sender_state(const struct nf_sender *sender, const struct nf_ingest_transport *transport, struct nf_stream_state *out_state);

// Close the stream on the platform (FinishStream). This does NOT upload: stop all writers,
// flush them, and run `nf_sender_run` until `nf_wal_len()` is 0 first. While the WAL still holds
// records, or while `nf_sender_run` is active, this returns `NF_ERR_INVALID_ARG` and does not
// call FinishStream (a closed stream can never receive them). If a writer adds records while
// FinishStream is in flight, the stream is closed but the call returns `NF_ERR_INVALID_ARG`
// reporting how many records can no longer be uploaded; on that error the stream IS closed but,
// as for every error, `out_state` is not written (call `nf_sender_state` to read it). To abandon
// unsent records on purpose, delete the WAL directory. (CABI-T2)
nf_status nf_sender_finish(const struct nf_sender *sender, const struct nf_ingest_transport *transport, struct nf_stream_state *out_state);

// Free the strings of a stream state (NULL is a no-op).
void nf_stream_state_free(struct nf_stream_state *state);

// Sender counters (thread-safe).
nf_status nf_sender_get_stats(const struct nf_sender *sender, struct nf_sender_stats *out_stats);

// The fatal error that stopped the sender; `NF_ERR_NOT_FOUND` if there is none.
nf_status nf_sender_fatal_error(const struct nf_sender *sender, struct nf_buf *out_message);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NEUROFORGE_H */
