// Console build config + security headers (SEC-150..156 applied to the console; SEC-015 notes in
// README). Zero dependencies; imported by vite.config.ts, scripts/postbuild.mjs, the dist tests and
// e2e/serve.mjs.
//
// Build-time environment:
//   NF_CONSOLE_OIDC_ISSUER     issuer URL (https://...), or a path such as /mock-idp (dev/e2e only)
//   NF_CONSOLE_OIDC_CLIENT_ID  public client ID (default nf-console)
//   NF_CONSOLE_OIDC_SCOPE      extra scopes after "openid" (default "openid profile")
//   NF_CONSOLE_OIDC_AUDIENCE   optional audience parameter
//   NF_CONSOLE_API_BASE        API origin, "" = same origin (default)
//   NF_CONSOLE_STAGE           preview|launch|public (HSTS per SEC-151; default preview)

export const STAGES = ['preview', 'launch', 'public'];

export function consoleConfig(env = process.env) {
  const v = (k, d) => (env[k] && env[k].trim() ? env[k].trim() : d);
  return {
    issuer: v('NF_CONSOLE_OIDC_ISSUER', '/mock-idp').replace(/\/+$/, ''),
    clientId: v('NF_CONSOLE_OIDC_CLIENT_ID', 'nf-console'),
    scope: v('NF_CONSOLE_OIDC_SCOPE', 'openid profile'),
    audience: v('NF_CONSOLE_OIDC_AUDIENCE', ''),
    apiBase: v('NF_CONSOLE_API_BASE', '').replace(/\/+$/, ''),
  };
}

function originOf(url, what) {
  if (!url || url.startsWith('/')) return null; // same origin
  const u = new URL(url);
  if (u.protocol !== 'https:') throw new Error(`${what} must be https (got ${url})`);
  if (u.username || u.password) throw new Error(`${what} must not carry credentials`);
  return u.origin;
}

/** Non-self origins the console must reach: the IdP (discovery/token) and the API, if separate. */
export function connectOrigins(config) {
  const out = [originOf(config.issuer, 'issuer'), originOf(config.apiBase, 'API base')].filter(
    Boolean,
  );
  return [...new Set(out)].sort();
}

export function resolveStage(value = process.env.NF_CONSOLE_STAGE) {
  const stage = value && value.trim() ? value.trim() : 'preview';
  if (!STAGES.includes(stage))
    throw new Error(`NF_CONSOLE_STAGE must be one of ${STAGES.join('|')}`);
  return stage;
}

export function hsts(stage) {
  return {
    preview: 'max-age=300',
    launch: 'max-age=86400',
    public: 'max-age=63072000; includeSubDomains; preload',
  }[resolveStage(stage)];
}

/**
 * SEC-150 for the console: same directives as the website, plus the configured IdP/API origins in
 * connect-src only. Trusted Types are required (no string-to-script sinks at all: React renders
 * through the DOM API and the build emits no inline code).
 */
export function csp({ connect = [] } = {}) {
  return [
    "default-src 'none'",
    "script-src 'self'",
    "style-src 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    ["connect-src 'self'", ...connect].join(' '),
    "manifest-src 'self'",
    "worker-src 'self'",
    "media-src 'self'",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "require-trusted-types-for 'script'",
    "trusted-types 'none'",
    'upgrade-insecure-requests',
  ].join('; ');
}

export const PERMISSIONS_POLICY = [
  'accelerometer=()',
  'ambient-light-sensor=()',
  'autoplay=()',
  'bluetooth=()',
  'browsing-topics=()',
  'camera=()',
  'display-capture=()',
  'encrypted-media=()',
  'fullscreen=(self)',
  'geolocation=()',
  'gyroscope=()',
  'hid=()',
  'magnetometer=()',
  'microphone=()',
  'midi=()',
  'payment=()',
  'publickey-credentials-get=()',
  'screen-wake-lock=()',
  'serial=()',
  'usb=()',
  'xr-spatial-tracking=()',
].join(', ');

export function globalHeaders({ stage, connect = [] } = {}) {
  return {
    'Content-Security-Policy': csp({ connect }),
    'Strict-Transport-Security': hsts(stage),
    'Permissions-Policy': PERMISSIONS_POLICY,
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Cross-Origin-Resource-Policy': 'same-origin',
    'Cross-Origin-Embedder-Policy': 'require-corp',
  };
}

export const CACHE_IMMUTABLE = 'public, max-age=31536000, immutable';
/** The console shell and anything unhashed: never cached (tenant UI, frequent deploys). */
export const CACHE_HTML = 'no-store';
export const HASHED_ASSET_PREFIX = '/assets/';

export function renderHeadersFile({ stage, connect }) {
  const lines = [
    '# Generated by apps/console/scripts/postbuild.mjs from apps/console/security-headers.mjs. Do not edit.',
    `# NF_CONSOLE_STAGE=${resolveStage(stage)}`,
    '/*',
  ];
  for (const [k, v] of Object.entries(globalHeaders({ stage, connect })))
    lines.push(`  ${k}: ${v}`);
  lines.push(
    '/',
    `  Cache-Control: ${CACHE_HTML}`,
    '/index.html',
    `  Cache-Control: ${CACHE_HTML}`,
  );
  lines.push(`${HASHED_ASSET_PREFIX}*`, `  Cache-Control: ${CACHE_IMMUTABLE}`);
  return lines.join('\n') + '\n';
}

export function parseCsp(value) {
  const m = new Map();
  for (const part of value.split(';')) {
    const [name, ...sources] = part.trim().split(/\s+/).filter(Boolean);
    if (!name) continue;
    if (m.has(name)) throw new Error(`CSP: duplicate directive ${name}`);
    m.set(name, sources);
  }
  return m;
}

/** Throws on unsafe-*, wildcards, schemes other than data: in img-src, or unexpected hosts. */
export function assertCspSafe(value, { allowedOrigins = [] } = {}) {
  const d = parseCsp(value);
  for (const req of [
    'default-src',
    'script-src',
    'style-src',
    'object-src',
    'base-uri',
    'frame-ancestors',
  ])
    if (!d.has(req)) throw new Error(`CSP: missing ${req}`);
  for (const [name, sources] of d) {
    for (const s of sources) {
      if (/unsafe/i.test(s)) throw new Error(`CSP: ${name} has ${s}`);
      if (s.includes('*')) throw new Error(`CSP: ${name} has a wildcard`);
      if (/^'(self|none|script)'$/.test(s)) continue;
      if (name === 'img-src' && s === 'data:') continue;
      if (name === 'connect-src' && allowedOrigins.includes(s)) continue;
      throw new Error(`CSP: ${name} allows ${s}`);
    }
  }
}
